using System;
using System.Collections.Generic;

namespace Domain
{
    public static class HearthDb
    {
        public static Dictionary<string, CardData> CardBase { get; set; }

        public static int ManaCost(string cardName)
        {
            if (CardBase == null)
                LoadCardBase();

            var cardData = new CardData();
            if (CardBase.TryGetValue(cardName, out cardData))
            {
                return cardData.ManaCost;
            }
            return -1;
        }

        public static int ManaCost(Card card)
        {
            if (CardBase == null)
                LoadCardBase();

            var cardData = new CardData();
            if (CardBase.TryGetValue(card.Name, out cardData))
            {
                return cardData.ManaCost;
            }
            return -1;
        }

        public static bool HasAoe(Card card)
        {
            if (CardBase == null)
                LoadCardBase();
            var cardData = new CardData();
            if (CardBase.TryGetValue(card.Name, out cardData))
            {
                return cardData.Aoe;
            }
            return false;
        }


        private static void LoadCardBase()
        {
            CardBase = new Dictionary<string, CardData>
            {
{ "Acidic Swamp Ooze", new CardData { ManaCost = 2 } },
{ "Acolyte of Pain", new CardData { ManaCost = 3 } },
{ "Alexstrasza", new CardData { ManaCost = 9 } },
{ "Alleycat", new CardData { ManaCost = 1 } },
{ "Aluneth", new CardData { ManaCost = 0 } },
{ "Animal Companion", new CardData { ManaCost = 3 } },
{ "Arcane Artificer", new CardData { ManaCost = 1 } },
{ "Arcane Intellect", new CardData { ManaCost = 3 } },
{ "Arcanite Reaper", new CardData { ManaCost = 5 } },
{ "Arcanologist", new CardData { ManaCost = 2 } },
{ "Archmage Antonidas", new CardData { ManaCost = 7 } },
{ "Argent Squire", new CardData { ManaCost = 1 } },
{ "Aya Blackpaw", new CardData { ManaCost = 4} },
{ "Babbling Book", new CardData { ManaCost = 1 } },
{ "Backstab", new CardData { ManaCost = 0 } },
{ "Barnes", new CardData { ManaCost = 4 } },
{ "Beckoner of Evil", new CardData { ManaCost = 2 } },
{ "Bittertide Hydra", new CardData { ManaCost = 5 } },
{ "Blazecaller", new CardData { ManaCost = 7 } },
{ "Blizzard", new CardData { ManaCost = 6, Aoe = true } },
{ "Blood Razor", new CardData { ManaCost = 4 } },
{ "Bloodfury Potion", new CardData { ManaCost = 3, Aoe = true } },
{ "Bloodlust", new CardData { ManaCost = 5 } },
{ "Bloodreaver Gul'dan", new CardData { ManaCost = 10 } },
{ "Bloodsail Cultist", new CardData { ManaCost = 3 } },
{ "Bloodsail Raider", new CardData { ManaCost = 2 } },
{ "Bluegill Warrior", new CardData { ManaCost = 2 } },
{ "Book Wyrm", new CardData { ManaCost = 6 } },
{ "Branching Paths", new CardData { ManaCost = 4 } },
{ "Brawl", new CardData { ManaCost = 5, Aoe = true } },
{ "Bright-Eyed Scout", new CardData { ManaCost = 4 } },
{ "Bring It On!", new CardData { ManaCost = 2 } },
{ "Cabal Shadow Priest", new CardData { ManaCost = 6 } },
{ "Cabalist's Tome", new CardData { ManaCost = 5 } },
{ "Cairn Bloodhoof", new CardData { ManaCost = 6 } },
{ "Call of the Wild", new CardData { ManaCost = 8 } },
{ "Call to Arms", new CardData { ManaCost = 4 } },
{ "Candleshot", new CardData { ManaCost = 1 } },
{ "Captain Greenskin", new CardData { ManaCost = 5 } },
{ "Carnivorous Cube", new CardData { ManaCost = 5 } },
{ "Cat Trick", new CardData { ManaCost = 2 } },
{ "Cavern Shinyfinder", new CardData { ManaCost = 2 } },
{ "Cobalt Scalebane", new CardData { ManaCost = 5 } },
{ "Cold Blood", new CardData { ManaCost = 1 } },
{ "Coldlight Oracle", new CardData { ManaCost = 3 } },
{ "Coldlight Seer", new CardData { ManaCost = 3 } },
{ "Consecration", new CardData { ManaCost = 4 , Aoe = true} },
{ "Corridor Creeper", new CardData { ManaCost = 7 } },
{ "Counterfeit Coin", new CardData { ManaCost = 0 } },
{ "Counterspell", new CardData { ManaCost = 3 } },
{ "Crackling Razormaw", new CardData { ManaCost = 2 } },
{ "Crystalweaver", new CardData { ManaCost = 4 } },
{ "C'Thun", new CardData { ManaCost = 10 } },
{ "C'Thun's Chosen", new CardData { ManaCost = 4 } },
{ "Curious Glimmerroot", new CardData { ManaCost = 3 } },
{ "Crystal Lion", new CardData { ManaCost = 6 } },
{ "Dark Arakkoa", new CardData { ManaCost = 6 } },
{ "Dark Pact", new CardData { ManaCost = 1 } },
{ "Dead Man's Hand", new CardData { ManaCost = 2 } },
{ "Deadly Poison", new CardData { ManaCost = 1 } },
{ "Deadly Shot", new CardData { ManaCost = 3 } },
{ "Deathstalker Rexxar", new CardData { ManaCost = 6, Aoe = true } },
{ "Deathwing", new CardData { ManaCost = 10 } },
{ "Deathwing, Dragonlord", new CardData { ManaCost = 10 } },
{ "Defile", new CardData { ManaCost = 2, Aoe = true } },
{ "Demonfire", new CardData { ManaCost = 1 } },
{ "Despicable Dreadlord", new CardData { ManaCost = 5, Aoe = true } },
{ "Devolve", new CardData { ManaCost = 2, Aoe = true } },
{ "Dire Mole", new CardData { ManaCost = 1 } },
{ "Dire Wolf Alpha", new CardData { ManaCost = 2 } },
{ "Dirty Rat", new CardData { ManaCost = 2 } },
{ "Disciple of C'Thun", new CardData { ManaCost = 3 } },
{ "Divine Favor", new CardData { ManaCost = 3 } },
{ "Divine Spirit", new CardData { ManaCost = 2 } },
{ "Doomerang", new CardData { ManaCost = 1 } },
{ "Doomguard", new CardData { ManaCost = 5 } },
{ "Doomsayer", new CardData { ManaCost = 2, Aoe = true  } },
{ "Dopplegangster", new CardData { ManaCost = 5 } },
{ "Dragoncaller Alanna", new CardData { ManaCost = 9 } },
{ "Dragonhatcher", new CardData { ManaCost = 9 } },
{ "Dragon's Fury", new CardData { ManaCost = 5, Aoe = true } },
{ "Drakkari Enchanter", new CardData { ManaCost = 3 } },
{ "Drakonid Operative", new CardData { ManaCost = 5 } },
{ "Dread Corsair", new CardData { ManaCost = 4 } },
{ "Druid of the Swarm", new CardData { ManaCost = 2 } },
{ "Drygulch Jailor", new CardData { ManaCost = 2 } },
{ "Drywhisker Armorer", new CardData { ManaCost = 2 } },
{ "Duskbreaker", new CardData { ManaCost = 4 , Aoe = true} },
{ "Eaglehorn Bow", new CardData { ManaCost = 3 } },
{ "Earthen Scales", new CardData { ManaCost = 1 } },
{ "Edwin VanCleef", new CardData { ManaCost = 3 } },
{ "Elise the Trailblazer", new CardData { ManaCost = 5 } },
{ "Elven Minstrel", new CardData { ManaCost = 4 } },
{ "Enchanted Raven", new CardData { ManaCost = 1 } },
{ "Equality", new CardData { ManaCost = 2, Aoe = true } },
{ "Eternal Servitude", new CardData { ManaCost = 4 } },
{ "Eviscerate", new CardData { ManaCost = 1 } },
{ "Evolve", new CardData { ManaCost =  1 } },
{ "Execute", new CardData { ManaCost = 2 } },
{ "Explosive Runes", new CardData { ManaCost = 3 } },
{ "Explosive Trap", new CardData { ManaCost = 2, Aoe = true } },
{ "Faceless Manipulator", new CardData { ManaCost = 5 } },
{ "Fal'dorei Strider", new CardData { ManaCost = 4 } },
{ "Fan of Knives", new CardData { ManaCost = 3, Aoe = true } },
{ "Fandral Staghelm", new CardData { ManaCost = 4 } },
{ "Fiery War Axe", new CardData { ManaCost = 2 } },
{ "Finja the Flying Star", new CardData { ManaCost = 5 } },
{ "Fire Fly", new CardData { ManaCost = 1 } },
{ "Fire Plume Phoenix", new CardData { ManaCost = 4 } },
{ "Fireball", new CardData { ManaCost = 4 } },
{ "Firelands Portal", new CardData { ManaCost = 7 } },
{ "Flame Imp", new CardData { ManaCost = 1 } },
{ "Flamestrike", new CardData { ManaCost = 7, Aoe = true } },
{ "Flametongue Totem", new CardData { ManaCost = 2 } },
{ "Flanking Strike", new CardData { ManaCost = 4 } },
{ "Flare", new CardData { ManaCost = 2 } },
{ "Free From Amber", new CardData { ManaCost = 8 } },
{ "Freezing Trap", new CardData { ManaCost = 1 } },
{ "Frost Lich Jaina", new CardData { ManaCost = 9 } },
{ "Frost Nova", new CardData { ManaCost = 3 } },
{ "Frostbolt", new CardData { ManaCost = 2 } },
{ "Frothing Berserker", new CardData { ManaCost = 3 } },
{ "Fungalmancer", new CardData { ManaCost = 5 } },
{ "Gadgetzan Auctioneer", new CardData { ManaCost = 6 } },
{ "Gadgetzan Ferryman", new CardData { ManaCost = 2 } },
{ "Glacial Shard", new CardData { ManaCost = 1 } },
{ "Gentle Megasaur", new CardData { ManaCost = 4 } },
{ "Grand Archivist", new CardData { ManaCost = 8 } },
{ "Greater Healing Potion", new CardData { ManaCost = 4 } },
{ "Greedy Sprite", new CardData { ManaCost = 3 } },
{ "Grimscale Chum", new CardData { ManaCost = 1 } },
{ "Grumble Worldshaker", new CardData { ManaCost = 6 } },
{ "Harrison Jones", new CardData { ManaCost = 5 } },
{ "Healing Rain", new CardData { ManaCost = 3 } },
{ "Hellfire", new CardData { ManaCost = 4 , Aoe = true} },
{ "Heroic Strike", new CardData { ManaCost = 2 } },
{ "Hex", new CardData { ManaCost = 3 } },
{ "Holy Smite", new CardData { ManaCost = 1 } },
{ "Houndmaster", new CardData { ManaCost = 4 } },
{ "Hungry Crab", new CardData { ManaCost = 1 } },
{ "Hunter's Mark", new CardData { ManaCost = 1 } },
{ "Hydrologist", new CardData { ManaCost = 2 } },
{ "Ice Barrier", new CardData { ManaCost = 3 } },
{ "Ice Block", new CardData { ManaCost = 3 } },
{ "Inner Fire", new CardData { ManaCost = 1 } },
{ "Innervate", new CardData { ManaCost = 1 } },
{ "Jade Behemoth", new CardData { ManaCost = 6 } },
{ "Jade Blossom", new CardData { ManaCost = 3 } },
{ "Jade Chieftan", new CardData { ManaCost = 7 } },
{ "Jade Claws", new CardData { ManaCost = 4 } },
{ "Jade Idol", new CardData { ManaCost = 1 } },
{ "Jade Lightning", new CardData { ManaCost = 4 } },
{ "Jade Spirit", new CardData { ManaCost = 4 } },
{ "Jinyu Waterspeaker", new CardData { ManaCost = 4 } },
{ "Kabal Crystal Runner", new CardData { ManaCost = 6 } },
{ "Kabal Lackey", new CardData { ManaCost = 1 } },
{ "Kabal Songstealer", new CardData { ManaCost = 5 } },
{ "Kabal Talonpriest", new CardData { ManaCost = 3 } },
{ "Kill Command", new CardData { ManaCost = 3 } },
{ "Kindly Grandmother", new CardData { ManaCost = 2 } },
{ "Kingsbane", new CardData { ManaCost = 1 } },
{ "Kirin Tor Mage", new CardData { ManaCost = 3 } },
{ "Knife Juggler", new CardData { ManaCost = 2 } },
{ "Kobold Librarian", new CardData { ManaCost = 1 } },
{ "Kor'kron Elite", new CardData { ManaCost = 3 } },
{ "Kun the Forgotten King", new CardData { ManaCost = 10 } },
{ "Leeching Poison", new CardData { ManaCost = 2 } },
{ "Leeroy Jenkins", new CardData { ManaCost = 5 } },
{ "Lesser Amethyst Spellstone", new CardData { ManaCost = 4 } },
{ "Lesser Diamond Spellstone", new CardData { ManaCost = 7 } },
{ "Lesser Emerald Spellstone", new CardData { ManaCost = 5 } },
{ "Lesser Jasper Spellstone", new CardData { ManaCost = 1 } },
{ "Level Up!", new CardData { ManaCost = 5, Aoe = true } },
{ "Lightfused Stegodon", new CardData { ManaCost = 4 } },
{ "Living Mana", new CardData { ManaCost = 5 , Aoe = true} },
{ "Loot Hoarder", new CardData { ManaCost = 2 } },
{ "Lost in the Jungle", new CardData { ManaCost = 1 } },
{ "Maelstrom Portal", new CardData { ManaCost = 1 , Aoe = true} },
{ "Malchezaar's Imp", new CardData { ManaCost = 1 } },
{ "Malfurion the Pestilent", new CardData { ManaCost = 7 } },
{ "Malygos", new CardData { ManaCost = 9 } },
{ "Mana Bind", new CardData { ManaCost = 3 } },
{ "Mana Tide Totem", new CardData { ManaCost = 3 } },
{ "Mana Wyrm", new CardData { ManaCost = 1 } },
{ "Mark of the Lotus", new CardData { ManaCost = 1 } },
{ "Mark of Y'Shaarj", new CardData { ManaCost = 2 } },
{ "Mass Dispel", new CardData { ManaCost = 4 } },
{ "Master Oakheart", new CardData { ManaCost = 9 } },
{ "Master of Evolution", new CardData { ManaCost = 4 } },
{ "Medivh the Guardian", new CardData { ManaCost = 8 } },
{ "Medivh's Valet", new CardData { ManaCost = 2 } },
{ "Meteor", new CardData { ManaCost = 6, Aoe = true } },
{ "Mimic Pod", new CardData { ManaCost = 3 } },
{ "Mind Blast", new CardData { ManaCost = 2 } },
{ "Mind Control", new CardData { ManaCost = 10 } },
{ "Mind Control Tech", new CardData { ManaCost = 3 } },
{ "Mire Keeper", new CardData { ManaCost = 4 } },
{ "Mistress of Mixtures", new CardData { ManaCost = 1 } },
{ "Molten Reflection", new CardData { ManaCost = 4 } },
{ "Mortal Coil", new CardData { ManaCost = 1 } },
{ "Mountain Giant", new CardData { ManaCost = 12 } },
{ "Murloc Tidecaller", new CardData { ManaCost = 1 } },
{ "Murloc Warleader", new CardData { ManaCost = 3 } },
{ "Murmuring Elemental", new CardData { ManaCost = 2 } },
{ "Nage Corsair", new CardData { ManaCost = 4 } },
{ "Netherspite Historian", new CardData { ManaCost = 2 } },
{ "Northshire Cleric", new CardData { ManaCost = 1 } },
{ "Nourish", new CardData { ManaCost = 5 } },
{ "Novice Engineer", new CardData { ManaCost = 2 } },
{ "N'Zoth the Corruptor", new CardData { ManaCost = 10 } },
{ "N'Zoth's First Mate", new CardData { ManaCost = 1 } },
{ "Oaken Summons", new CardData { ManaCost = 4 } },
{ "Obsidian Statue", new CardData { ManaCost = 9 } },
{ "Open the Waygate", new CardData { ManaCost = 1 } },
{ "Patches the Pirate", new CardData { ManaCost = 1 } },
{ "Pint-Size Potion", new CardData { ManaCost = 1 } },
{ "Plated Beetle", new CardData { ManaCost = 2 } },
{ "Polymorph", new CardData { ManaCost = 4 } },
{ "Possessed Lackey", new CardData { ManaCost = 5 } },
{ "Potion of Madness", new CardData { ManaCost = 1 } },
{ "Power of the Wild", new CardData { ManaCost = 2 } },
{ "Power Word: Shield", new CardData { ManaCost = 1 } },
{ "Preparation", new CardData { ManaCost = 0 } },
{ "Priest of the Feast", new CardData { ManaCost = 4 } },
{ "Primordial Drake", new CardData { ManaCost = 8 } },
{ "Primordial Glyph", new CardData { ManaCost = 2 } },
{ "Prince Keleseth", new CardData { ManaCost = 2 } },
{ "Prince Taldaram", new CardData { ManaCost = 3 } },
{ "Prophet Velen", new CardData { ManaCost = 7 } },
{ "Psychic Scream", new CardData { ManaCost = 7, Aoe = true } },
{ "Pyroblast", new CardData { ManaCost = 10 } },
{ "Radiant Elemental", new CardData { ManaCost = 2 } },
{ "Ragnaros Lightlord", new CardData { ManaCost = 8 } },
{ "Rallying Blade", new CardData { ManaCost = 3 } },
{ "Raven Familiar", new CardData { ManaCost = 2 } },
{ "Rhok'delar", new CardData { ManaCost = 7 } },
{ "Righteous Protector", new CardData { ManaCost = 1 } },
{ "Rin the First Disciple", new CardData { ManaCost = 6 } },
{ "Rockpool Hunter", new CardData { ManaCost = 2 } },
{ "Rummaging Kobold", new CardData { ManaCost = 3 } },
{ "Sap", new CardData { ManaCost = 2 } },
{ "Saronite Chang Gang", new CardData { ManaCost = 4 } },
{ "Savage Roar", new CardData { ManaCost = 3 } },
{ "Scavenging Hyena", new CardData { ManaCost = 2 } },
{ "Scourgelord Garrosh", new CardData { ManaCost = 8 } },
{ "Shadow Ascendant", new CardData { ManaCost = 2 } },
{ "Shadow Essence", new CardData { ManaCost = 6 } },
{ "Shadow Visions", new CardData { ManaCost = 2 } },
{ "Shadow Word: Death", new CardData { ManaCost = 3 } },
{ "Shadow Word: Horror", new CardData { ManaCost = 4 } },
{ "Shadowcaster", new CardData { ManaCost = 5 } },
{ "Shadowreaper Anduin", new CardData { ManaCost = 8 } },
{ "Shadowstep", new CardData { ManaCost = 0 } },
{ "Shield Block", new CardData { ManaCost = 3 } },
{ "Shield Slam", new CardData { ManaCost = 1 } },
{ "Shiv", new CardData { ManaCost = 2 } },
{ "SI:7 Agent", new CardData { ManaCost = 3 } },
{ "Siphon Soul", new CardData { ManaCost = 6 } },
{ "Skulking Geist", new CardData { ManaCost = 6 } },
{ "Skull of the Man'ari", new CardData { ManaCost = 5 } },
{ "Slam", new CardData { ManaCost = 2 } },
{ "Sleep with the Fishes", new CardData { ManaCost = 2, Aoe = true } },
{ "Sleepy Dragon", new CardData { ManaCost = 9 } },
{ "Sonya Shadowdancer", new CardData { ManaCost = 3 } },
{ "Sorcerer's Apprentice", new CardData { ManaCost = 2 } },
{ "Soulfire", new CardData { ManaCost = 1 } },
{ "Southsea Captain", new CardData { ManaCost = 3 } },
{ "Southsea Deckhand", new CardData { ManaCost = 1 } },
{ "Southsea Squidface", new CardData { ManaCost = 4 } },
{ "Spellbreaker", new CardData { ManaCost = 4 } },
{ "Spikeridged Steed", new CardData { ManaCost = 6 } },
{ "Spirit Lash", new CardData { ManaCost = 2, Aoe = true } },
{ "Spiteful Summoner", new CardData { ManaCost = 6 } },
{ "Spreading Plague", new CardData { ManaCost = 5 } },
{ "Stand Against Darkness", new CardData { ManaCost = 5 } },
{ "Steward of Darkshire", new CardData { ManaCost = 3 } },
{ "Stonehill Defender", new CardData { ManaCost = 3 } },
{ "Stonetusk Boar", new CardData { ManaCost = 1 } },
{ "Sunkeeper Tarim", new CardData { ManaCost = 6 } },
{ "Swipe", new CardData { ManaCost = 4 , Aoe = true} },
{ "Tar Creeper", new CardData { ManaCost = 3 } },
{ "The Caverns Below", new CardData { ManaCost = 1 } },
{ "The Lich King", new CardData { ManaCost = 8 } },
{ "Thrall Deathseer", new CardData { ManaCost = 5 } },
{ "Tirion Fordring", new CardData { ManaCost = 8 } },
{ "Tracking", new CardData { ManaCost = 1 } },
{ "Twilight Acolyte", new CardData { ManaCost = 3 } },
{ "Twilight Drake", new CardData { ManaCost = 4 } },
{ "Twilight Elder", new CardData { ManaCost = 3 } },
{ "Twin Emperor Vak'lor", new CardData { ManaCost = 7 } },
{ "Twisting Nether", new CardData { ManaCost = 8 , Aoe = true} },
{ "Ultimate Infestation", new CardData { ManaCost = 10 } },
{ "Unidentified Maul", new CardData { ManaCost = 3 } },
{ "Unleash the Hounds", new CardData { ManaCost = 3 , Aoe = true} },
{ "Unlicensed Apothecary", new CardData { ManaCost = 3 } },
{ "Unstable Evolution", new CardData { ManaCost = 1 } },
{ "Upgrade!", new CardData { ManaCost = 0 } },
{ "Uther of the Ebon Blade", new CardData { ManaCost = 9 } },
{ "Val'anyr", new CardData { ManaCost = 6 } },
{ "Valeera the Hollow", new CardData { ManaCost = 9 } },
{ "Vanish", new CardData { ManaCost = 6 } },
{ "Vilefin Inquisitor", new CardData { ManaCost = 1 } },
{ "Vilespine Slayer", new CardData { ManaCost = 5 } },
{ "Vinecleaver", new CardData { ManaCost = 7 } },
{ "Violent Teacher", new CardData { ManaCost = 4 } },
{ "Viscious Fledgling", new CardData { ManaCost = 3 } },
{ "Voidlord", new CardData { ManaCost = 9 } },
{ "Voidwalker", new CardData { ManaCost = 1 } },
{ "Volcano", new CardData { ManaCost = 5, Aoe = true } },
{ "Vulgar Homunculus", new CardData { ManaCost = 2 } },
{ "Wandering Monster", new CardData { ManaCost = 2 } },
{ "Wax Elemental", new CardData { ManaCost = 1 } },
{ "Whirlwind", new CardData { ManaCost = 1 , Aoe = true} },
{ "Wild Growth", new CardData { ManaCost = 2 } },
{ "Wild Pyromancer", new CardData { ManaCost = 2 } },
{ "Youthful Brewmaster", new CardData { ManaCost = 2 } },
{ "Ysera", new CardData { ManaCost = 9 } },
{ "Y'Shaarj Rage Unbound", new CardData { ManaCost = 10 } },
{ "Zola the Gorgon", new CardData { ManaCost = 3 } }
            };
        }

    }

    public class CardData
    {
        public int ManaCost { get; set; }
        public bool Aoe { get; set; }
    }
}