using System;
using System.Collections.Generic;

namespace Domain
{
    public static class HearthDb
    {
        public static Dictionary<string, CardData> CardBase 
		{ 
			get; 
			set; 
		}

        public static int ManaCost(
			string cardName)
        {
            if (CardBase == null)
                LoadCardBase();

            if (CardBase.TryGetValue(
				cardName, 
				out CardData cardData))
            {
                return cardData.ManaCost;
            }
            return -1;
        }

        public static int ManaCost(
			Card card)
        {
            if (CardBase == null)
                LoadCardBase();

            if (CardBase.TryGetValue(
				card.Name, 
				out CardData cardData))
            {
                return cardData.ManaCost;
            }
            return -1;
        }

        public static bool HasAoe(
			Card card)
        {
            if (CardBase == null)
                LoadCardBase();
			if (CardBase.TryGetValue(
				card.Name, 
				out CardData cardData))
			{
				return cardData.Aoe;
			}
			return false;
        }

		public static bool IsSecret(Card card)
		{
			if (CardBase == null)
				LoadCardBase();
			if (CardBase.TryGetValue(
				card.Name, 
				out CardData cardData))
			{
				return cardData.IsSecret;
			}
			return false;
		}

		public static bool IsWeapon(Card card)
		{
			if (CardBase == null)
				LoadCardBase();
			if (CardBase.TryGetValue(
				card.Name, 
				out CardData cardData))
			{
				return cardData.IsWeapon;
			}
			return false;
		}

		public static bool IsWeaponRemoval(
			Card card)
		{
			if (CardBase == null)
				LoadCardBase();
			if (CardBase.TryGetValue(
				card.Name,
				out CardData cardData))
			{
				return cardData.IsWeaponRemoval;
			}
			return false;
		}

		public static bool IsRemoval(Card card)
		{
			if (CardBase == null)
				LoadCardBase();
			if (CardBase.TryGetValue(
				card.Name, 
				out CardData cardData))
			{
				return cardData.IsRemoval;
			}
			return false;
		}

		internal static int? AttackFor(
			string cardName)
		{
			if (CardBase == null)
				LoadCardBase();

			if (CardBase.TryGetValue(
				cardName,
				out CardData cardData))
			{
				return cardData.Attack;
			}
			return null;
		}

		internal static bool Taunt(
			string cardName)
		{
			if (CardBase == null)
				LoadCardBase();

			if (CardBase.TryGetValue(
				cardName,
				out CardData cardData))
			{
				return cardData.IsTaunt;
			}
			return false;
		}


		internal static bool DivineShield(
			string cardName)
		{
			if (CardBase == null)
				LoadCardBase();

			if (CardBase.TryGetValue(
				cardName,
				out CardData cardData))
			{
				return cardData.HasShield;
			}
			return false;
		}

		internal static int? HealthFor(
			string cardName)
		{
			if (CardBase == null)
				LoadCardBase();

			if (CardBase.TryGetValue(
				cardName,
				out CardData cardData))
			{
				return cardData.Health;
			}
			return null;
		}

		internal static string SpellFor(
			string cardName)
		{
			if (CardBase == null)
				LoadCardBase();

			if (CardBase.TryGetValue(
				cardName,
				out CardData cardData))
			{
				return cardData.Spell;
			}
			return null;
		}

		public static bool IsBurn(
			Card card)
		{
			if (CardBase == null)
				LoadCardBase();
			if (CardBase.TryGetValue(
				card.Name, 
				out CardData cardData))
			{
				return cardData.IsBurn;
			}
			return false;
		}

		public static bool Contains(
			Card card)
		{
			if (CardBase == null)
				LoadCardBase();
			if (CardBase.TryGetValue(
				card.Name, 
				out _))
			{
				return true;
			}
			return false;
		}

        private static void LoadCardBase()
        {
            CardBase = new Dictionary<string, CardData>
            {
{ "Acidic Swamp Ooze", new CardData { ManaCost = 2 } },
{ "Acolyte of Pain", new CardData { ManaCost = 3 } },
{ "Alexstrasza", new CardData { ManaCost = 9, IsBurn = true } },
{ "Alleycat", new CardData { ManaCost = 1 } },
{ "Aluneth", new CardData { ManaCost = 6, IsWeapon = true } },
{ "Animal Companion", new CardData { ManaCost = 3 } },
{ "Arcane Artificer", new CardData { ManaCost = 1 } },
{ "Mo'arg Artificer", new CardData { ManaCost = 2 } },
{ "Arcane Intellect", new CardData { ManaCost = 3 } },
{ "Arcanite Reaper", new CardData { ManaCost = 5, IsWeapon = true } },
{ "Arcanologist", new CardData { ManaCost = 2 } },
{ "Archmage Antonidas", new CardData { ManaCost = 7 } },
{ "Argent Squire", new CardData { ManaCost = 1 } },
{ "Aya Blackpaw", new CardData { ManaCost = 4} },
{ "Babbling Book", new CardData { ManaCost = 1 } },
{ "Backstab", new CardData { ManaCost = 0 } },
{ "Barnes", new CardData { ManaCost = 4 } },
{ "Beckoner of Evil", new CardData { ManaCost = 2 } },
{ "Bittertide Hydra", new CardData { ManaCost = 5 } },
{ "Blazecaller", new CardData { ManaCost = 7 } },
{ "Blizzard", new CardData { ManaCost = 6, Aoe = true } },
{ "Blood Razor", new CardData { ManaCost = 4, IsWeapon = true } },
{ "Blood Knight", new CardData { ManaCost = 3 } },
{ "Bloodfury Potion", new CardData { ManaCost = 3, Aoe = true } },
{ "Bloodlust", new CardData { ManaCost = 5 } },
{ "Bloodreaver Gul'dan", new CardData { ManaCost = 10 } },
{ "Bloodsail Cultist", new CardData { ManaCost = 3 } },
{ "Bloodsail Raider", new CardData { ManaCost = 2 } },
{ "Bluegill Warrior", new CardData { ManaCost = 2 } },
{ "Book Wyrm", new CardData { ManaCost = 6 } },
{ "Branching Paths", new CardData { ManaCost = 4 } },
{ "Brawl", new CardData { ManaCost = 5, Aoe = true } },
{ "Bright-Eyed Scout", new CardData { ManaCost = 4 } },
{ "Bring It On!", new CardData { ManaCost = 2 } },
{ "Cabal Shadow Priest", new CardData { ManaCost = 6,  Attack = 4, Health = 5, Spell = "steal a minion with 2 or less attack" } },
{ "Cabalist's Tome", new CardData { ManaCost = 5 } },
{ "Cairn Bloodhoof", new CardData { ManaCost = 6 } },
{ "Call of the Wild", new CardData { ManaCost = 8 } },
{ "Call to Arms", new CardData { ManaCost = 4 } },
{ "Candleshot", new CardData { ManaCost = 1, IsWeapon = true } },
{ "Captain Greenskin", new CardData { ManaCost = 5 } },
{ "Carnivorous Cube", new CardData { ManaCost = 5 } },
{ "Cat Trick", new CardData { ManaCost = 2, IsSecret = true } },
{ "Cavern Shinyfinder", new CardData { ManaCost = 2 } },
{ "Cobalt Scalebane", new CardData { ManaCost = 5 } },
{ "Cold Blood", new CardData { ManaCost = 1, Spell = "buff minion +2 attack, combo +4" } },
{ "Coldlight Oracle", new CardData { ManaCost = 3 } },
{ "Coldlight Seer", new CardData { ManaCost = 3 } },
{ "Consecration", new CardData { ManaCost = 4 , Aoe = true} },
{ "Corridor Creeper", new CardData { ManaCost = 7 } },
{ "Counterfeit Coin", new CardData { ManaCost = 0 } },
{ "Counterspell", new CardData { ManaCost = 3, IsSecret = true } },
{ "Crackling Razormaw", new CardData { ManaCost = 2 } },
{ "Crystalweaver", new CardData { ManaCost = 4 } },
{ "C'Thun", new CardData { ManaCost = 10 } },
{ "C'Thun's Chosen", new CardData { ManaCost = 4 } },
{ "Curious Glimmerroot", new CardData { ManaCost = 3 } },
{ "Crystal Lion", new CardData { ManaCost = 6 } },
{ "Dark Arakkoa", new CardData { ManaCost = 6 } },
{ "Dark Pact", new CardData { ManaCost = 1 } },
{ "Dead Man's Hand", new CardData { ManaCost = 2 } },
{ "Deadly Poison", new CardData { ManaCost = 1 } },
{ "Deadly Shot", new CardData { ManaCost = 3, IsRemoval = true } },
{ "Deathstalker Rexxar", new CardData { ManaCost = 6, Aoe = true } },
{ "Deathwing", new CardData { ManaCost = 10 } },
{ "Deathwing, Dragonlord", new CardData { ManaCost = 10 } },
{ "Defile", new CardData { ManaCost = 2, Aoe = true } },
{ "Demonfire", new CardData { ManaCost = 1 } },
{ "Despicable Dreadlord", new CardData { ManaCost = 5, Aoe = true } },
{ "Devolve", new CardData { ManaCost = 2, Aoe = true } },
{ "Dire Mole", new CardData { ManaCost = 1 } },
{ "Dire Wolf Alpha", new CardData { ManaCost = 2 } },
{ "Dirty Rat", new CardData { ManaCost = 2 } },
{ "Disciple of C'Thun", new CardData { ManaCost = 3 } },
{ "Divine Favor", new CardData { ManaCost = 3 } },
{ "Divine Spirit", new CardData { ManaCost = 2 } },
{ "Doomerang", new CardData { ManaCost = 1 } },
{ "Doomguard", new CardData { ManaCost = 5 } },
{ "Doomsayer", new CardData { ManaCost = 2, Aoe = true, Attack = 0, Health = 7  } },
{ "Dopplegangster", new CardData { ManaCost = 5 } },
{ "Dragoncaller Alanna", new CardData { ManaCost = 9 } },
{ "Dragonhatcher", new CardData { ManaCost = 9 } },
{ "Dragon's Fury", new CardData { ManaCost = 5, Aoe = true } },
{ "Drakkari Enchanter", new CardData { ManaCost = 3 } },
{ "Drakonid Operative", new CardData { ManaCost = 5 } },
{ "Dread Corsair", new CardData { ManaCost = 4 } },
{ "Druid of the Swarm", new CardData { ManaCost = 2 } },
{ "Drygulch Jailor", new CardData { ManaCost = 2 } },
{ "Drywhisker Armorer", new CardData { ManaCost = 2 } },
{ "Duskbreaker", new CardData { ManaCost = 4 , Aoe = true} },
{ "Eaglehorn Bow", new CardData { ManaCost = 3, IsWeapon = true } },
{ "Earthen Scales", new CardData { ManaCost = 1 } },
{ "Edwin VanCleef", new CardData { ManaCost = 3, Attack = 2, Health = 2 } },
{ "Elise the Trailblazer", new CardData { ManaCost = 5 } },
{ "Elven Minstrel", new CardData { ManaCost = 4 } },
{ "Enchanted Raven", new CardData { ManaCost = 1 } },
{ "Equality", new CardData { ManaCost = 2, Aoe = true } },
{ "Eternal Servitude", new CardData { ManaCost = 4 } },
{ "Eviscerate", new CardData { ManaCost = 1, IsBurn = true } },
{ "Evolve", new CardData { ManaCost =  1 } },
{ "Execute", new CardData { ManaCost = 2, IsRemoval = true } },
{ "Explosive Runes", new CardData { ManaCost = 3, IsSecret = true } },
{ "Explosive Trap", new CardData { ManaCost = 2, Aoe = true, IsSecret = true } },
{ "Faceless Manipulator", new CardData { ManaCost = 5 } },
{ "Fal'dorei Strider", new CardData { ManaCost = 4 } },
{ "Fan of Knives", new CardData { ManaCost = 3, Aoe = true } },
{ "Fandral Staghelm", new CardData { ManaCost = 4 } },
{ "Fiery War Axe", new CardData { ManaCost = 2, IsWeapon = true } },
{ "Finja the Flying Star", new CardData { ManaCost = 5 } },
{ "Fire Fly", new CardData { ManaCost = 1 } },
{ "Fire Plume Phoenix", new CardData { ManaCost = 4 } },
{ "Fireball", new CardData { ManaCost = 4, IsBurn = true } },
{ "Firelands Portal", new CardData { ManaCost = 7 } },
{ "Flame Imp", new CardData { ManaCost = 1,  Attack = 3, Health = 2 } },
{ "Flamestrike", new CardData { ManaCost = 7, Aoe = true } },
{ "Flametongue Totem", new CardData { ManaCost = 2 } },
{ "Flanking Strike", new CardData { ManaCost = 4 } },
{ "Flare", new CardData { ManaCost = 2 } },
{ "Free From Amber", new CardData { ManaCost = 8 } },
{ "Freezing Trap", new CardData { ManaCost = 1, IsSecret = true } },
{ "Frost Lich Jaina", new CardData { ManaCost = 9 } },
{ "Frost Nova", new CardData { ManaCost = 3, Aoe = true } },
{ "Frostbolt", new CardData { ManaCost = 2, IsBurn = true } },
{ "Frothing Berserker", new CardData { ManaCost = 3 } },
{ "Fungalmancer", new CardData { ManaCost = 5 } },
{ "Gadgetzan Auctioneer", new CardData { ManaCost = 6 } },
{ "Gadgetzan Ferryman", new CardData { ManaCost = 2 } },
{ "Glacial Shard", new CardData { ManaCost = 1 } },
{ "Gentle Megasaur", new CardData { ManaCost = 4 } },
{ "Grand Archivist", new CardData { ManaCost = 8 } },
{ "Greater Healing Potion", new CardData { ManaCost = 4 } },
{ "Greedy Sprite", new CardData { ManaCost = 3 } },
{ "Grimscale Chum", new CardData { ManaCost = 1 } },
{ "Grumble Worldshaker", new CardData { ManaCost = 6 } },
{ "Harrison Jones", new CardData { ManaCost = 5, IsWeaponRemoval = true } },
{ "Healing Rain", new CardData { ManaCost = 3 } },
{ "Hellfire", new CardData { ManaCost = 4 , Aoe = true} },
{ "Heroic Strike", new CardData { ManaCost = 2 } },
{ "Hex", new CardData { ManaCost = 3, IsRemoval = true } },
{ "Holy Smite", new CardData { ManaCost = 1 } },
{ "Hemet Jungle Hunter", new CardData { ManaCost = 6 } },
{ "Houndmaster", new CardData { ManaCost = 4 } },
{ "Hungry Crab", new CardData { ManaCost = 1 } },
{ "Hunter's Mark", new CardData { ManaCost = 1 } },
{ "Hydrologist", new CardData { ManaCost = 2 } },
{ "Ice Barrier", new CardData { ManaCost = 3, IsSecret = true } },
{ "Ice Block", new CardData { ManaCost = 3, IsSecret = true } },
{ "Inner Fire", new CardData { ManaCost = 1 } },
{ "Innervate", new CardData { ManaCost = 1 } },
{ "Jade Behemoth", new CardData { ManaCost = 6 } },
{ "Jade Blossom", new CardData { ManaCost = 3 } },
{ "Jade Chieftan", new CardData { ManaCost = 7 } },
{ "Jade Claws", new CardData { ManaCost = 4 } },
{ "Jade Idol", new CardData { ManaCost = 1 } },
{ "Jade Lightning", new CardData { ManaCost = 4 } },
{ "Jade Spirit", new CardData { ManaCost = 4 } },
{ "Jinyu Waterspeaker", new CardData { ManaCost = 4 } },
{ "Kabal Crystal Runner", new CardData { ManaCost = 6 } },
{ "Kabal Lackey", new CardData { ManaCost = 1 } },
{ "Kabal Songstealer", new CardData { ManaCost = 5 } },
{ "Kabal Talonpriest", new CardData { ManaCost = 3 } },
{ "Kill Command", new CardData { ManaCost = 3, IsRemoval = true, IsBurn = true } },
{ "Kindly Grandmother", new CardData { ManaCost = 2 } },
{ "Kingsbane", new CardData { ManaCost = 1, IsWeapon = true } },
{ "Kirin Tor Mage", new CardData { ManaCost = 3 } },
{ "Knife Juggler", new CardData { ManaCost = 2 } },
{ "Kobold Librarian", new CardData { ManaCost = 1 } },
{ "Kor'kron Elite", new CardData { ManaCost = 3 } },
{ "Kun the Forgotten King", new CardData { ManaCost = 10 } },
{ "Leeching Poison", new CardData { ManaCost = 2 } },
{ "Leeroy Jenkins", new CardData { ManaCost = 5, IsBurn = true } },
{ "Lesser Amethyst Spellstone", new CardData { ManaCost = 4 } },
{ "Lesser Diamond Spellstone", new CardData { ManaCost = 7 } },
{ "Lesser Emerald Spellstone", new CardData { ManaCost = 5 } },
{ "Lesser Jasper Spellstone", new CardData { ManaCost = 1 } },
{ "Level Up!", new CardData { ManaCost = 5, Aoe = true } },
{ "Lightfused Stegodon", new CardData { ManaCost = 4 } },
{ "Sense Demons", new CardData { ManaCost = 4 } },
{ "Scrap Shot", new CardData { ManaCost = 4, IsBurn = true } },
{ "Living Mana", new CardData { ManaCost = 5 , Aoe = true} },
{ "Loot Hoarder", new CardData { ManaCost = 2 } },
{ "Imprisoned Felmaw", new CardData { ManaCost = 2 } },
{ "Lost in the Jungle", new CardData { ManaCost = 1 } },
{ "Maelstrom Portal", new CardData { ManaCost = 1 , Aoe = true} },
{ "Malchezaar's Imp", new CardData { ManaCost = 1 } },
{ "Malfurion the Pestilent", new CardData { ManaCost = 7 } },
{ "Malygos", new CardData { ManaCost = 9 } },
{ "Mana Bind", new CardData { ManaCost = 3 } },
{ "Mana Tide Totem", new CardData { ManaCost = 3 } },
{ "Mana Wyrm", new CardData { ManaCost = 1 } },
{ "Mark of the Lotus", new CardData { ManaCost = 1 } },
{ "Mark of Y'Shaarj", new CardData { ManaCost = 2 } },
{ "Mass Dispel", new CardData { ManaCost = 4 } },
{ "Master Oakheart", new CardData { ManaCost = 9 } },
{ "Master of Evolution", new CardData { ManaCost = 4 } },
{ "Medivh the Guardian", new CardData { ManaCost = 8 } },
{ "Medivh's Valet", new CardData { ManaCost = 2 } },
{ "Meteor", new CardData { ManaCost = 6, Aoe = true } },
{ "Mimic Pod", new CardData { ManaCost = 3 } },
{ "Mind Blast", new CardData { ManaCost = 2 , IsBurn = true} },
{ "Mind Control", new CardData { ManaCost = 10 } },
{ "Mind Control Tech", new CardData { ManaCost = 3 } },
{ "Mire Keeper", new CardData { ManaCost = 4 } },
{ "Mistress of Mixtures", new CardData { ManaCost = 1 } },
{ "Molten Reflection", new CardData { ManaCost = 4 } },
{ "Mortal Coil", new CardData { ManaCost = 1 } },
{ "Mortal Strike", new CardData { ManaCost = 4 } },
{ "Mountain Giant", new CardData { ManaCost = 12 } },
{ "Murloc Tidecaller", new CardData { ManaCost = 1 } },
{ "Murloc Warleader", new CardData { ManaCost = 3 } },
{ "Murmuring Elemental", new CardData { ManaCost = 2 } },
{ "Nage Corsair", new CardData { ManaCost = 4 } },
{ "Netherspite Historian", new CardData { ManaCost = 2 } },
{ "Northshire Cleric", new CardData { ManaCost = 1 } },
{ "Nourish", new CardData { ManaCost = 5 } },
{ "Novice Engineer", new CardData { ManaCost = 2 } },
{ "N'Zoth the Corruptor", new CardData { ManaCost = 10 } },
{ "N'Zoth's First Mate", new CardData { ManaCost = 1 } },
{ "Oaken Summons", new CardData { ManaCost = 4 } },
{ "Obsidian Statue", new CardData { ManaCost = 9 } },
{ "Open the Waygate", new CardData { ManaCost = 1 } },
{ "Patches the Pirate", new CardData { ManaCost = 1 } },
{ "Pint-Size Potion", new CardData { ManaCost = 1 } },
{ "Plated Beetle", new CardData { ManaCost = 2 } },
{ "Polymorph", new CardData { ManaCost = 4 } },
{ "Possessed Lackey", new CardData { ManaCost = 5 } },
{ "Potion of Madness", new CardData { ManaCost = 1 } },
{ "Power of the Wild", new CardData { ManaCost = 2 } },
{ "Power Word: Shield", new CardData { ManaCost = 1 } },
{ "Preparation", new CardData { ManaCost = 0 } },
{ "Priest of the Feast", new CardData { ManaCost = 4 } },
{ "Primordial Drake", new CardData { ManaCost = 8 } },
{ "Primordial Glyph", new CardData { ManaCost = 2 } },
{ "Prince Keleseth", new CardData { ManaCost = 2 } },
{ "Prince Taldaram", new CardData { ManaCost = 3 } },
{ "Prophet Velen", new CardData { ManaCost = 7 } },
{ "Psychic Scream", new CardData { ManaCost = 7, Aoe = true } },
{ "Pyroblast", new CardData { ManaCost = 10, IsBurn = true } },
{ "Radiant Elemental", new CardData { ManaCost = 2 } },
{ "Ragnaros Lightlord", new CardData { ManaCost = 8 } },
{ "Rallying Blade", new CardData { ManaCost = 3, IsWeapon = true } },
{ "Raven Familiar", new CardData { ManaCost = 2 } },
{ "Rhok'delar", new CardData { ManaCost = 7, IsWeapon = true } },
{ "Righteous Protector", new CardData { ManaCost = 1 } },
{ "Rin the First Disciple", new CardData { ManaCost = 6 } },
{ "Rockpool Hunter", new CardData { ManaCost = 2 } },
{ "Rummaging Kobold", new CardData { ManaCost = 3 } },
{ "Sap", new CardData { ManaCost = 2 } },
{ "Saronite Chang Gang", new CardData { ManaCost = 4 } },
{ "Savage Roar", new CardData { ManaCost = 3 } },
{ "Scavenging Hyena", new CardData { ManaCost = 2 } },
{ "Scourgelord Garrosh", new CardData { ManaCost = 8 } },
{ "Shadow Ascendant", new CardData { ManaCost = 2 } },
{ "Shadow Essence", new CardData { ManaCost = 6 } },
{ "Shadow Visions", new CardData { ManaCost = 2 } },
{ "Shadow Word: Death", new CardData { ManaCost = 2, IsRemoval = true } },
{ "Shadow Word: Horror", new CardData { ManaCost = 4 } },
{ "Shadowcaster", new CardData { ManaCost = 5 } },
{ "Shadowreaper Anduin", new CardData { ManaCost = 8, IsBurn = true } },
{ "Shadowstep", new CardData { ManaCost = 0 } },
{ "Shield Block", new CardData { ManaCost = 3 } },
{ "Shield Slam", new CardData { ManaCost = 1 } },
{ "Shiv", new CardData { ManaCost = 2 } },
{ "SI:7 Agent", new CardData { ManaCost = 3 } },
{ "Siphon Soul", new CardData { ManaCost = 6 } },
{ "Skulking Geist", new CardData { ManaCost = 6 } },
{ "Skull of the Man'ari", new CardData { ManaCost = 5 } },
{ "Slam", new CardData { ManaCost = 2 } },
{ "Sleep with the Fishes", new CardData { ManaCost = 2, Aoe = true } },
{ "Sleepy Dragon", new CardData { ManaCost = 9 } },
{ "Sonya Shadowdancer", new CardData { ManaCost = 3 } },
{ "Sorcerer's Apprentice", new CardData { ManaCost = 2, Attack = 3, Health = 2 } },
{ "Soulfire", new CardData { ManaCost = 1, IsBurn = true, Spell = "Discard 1 damage 4" } },
{ "Southsea Captain", new CardData { ManaCost = 3 } },
{ "Southsea Deckhand", new CardData { ManaCost = 1,  Attack = 2, Health = 1, Spell = "Charge if weapon"  } },
{ "Southsea Squidface", new CardData { ManaCost = 4 } },
{ "Spellbreaker", new CardData { ManaCost = 4 } },
{ "Spikeridged Steed", new CardData { ManaCost = 6 } },
{ "Spirit Lash", new CardData { ManaCost = 2, Aoe = true } },
{ "Spiteful Summoner", new CardData { ManaCost = 6 } },
{ "Spreading Plague", new CardData { ManaCost = 5 } },
{ "Stand Against Darkness", new CardData { ManaCost = 5 } },
{ "Steward of Darkshire", new CardData { ManaCost = 3 } },
{ "Stonehill Defender", new CardData { ManaCost = 3 } },
{ "Stonetusk Boar", new CardData { ManaCost = 1 } },
{ "Sunkeeper Tarim", new CardData { ManaCost = 6 } },
{ "Swipe", new CardData { ManaCost = 4 , Aoe = true} },
{ "Tar Creeper", new CardData { ManaCost = 3 } },
{ "The Caverns Below", new CardData { ManaCost = 1 } },
{ "The Lich King", new CardData { ManaCost = 8 } },
{ "Thrall Deathseer", new CardData { ManaCost = 5 } },
{ "Tirion Fordring", new CardData { ManaCost = 8 } },
{ "Tracking", new CardData { ManaCost = 1 } },
{ "Twilight Acolyte", new CardData { ManaCost = 3 } },
{ "Twilight Drake", new CardData { ManaCost = 4 } },
{ "Twilight Elder", new CardData { ManaCost = 3 } },
{ "Twin Emperor Vak'lor", new CardData { ManaCost = 7 } },
{ "Twisting Nether", new CardData { ManaCost = 8 , Aoe = true} },
{ "Ultimate Infestation", new CardData { ManaCost = 10 } },
{ "Unidentified Maul", new CardData { ManaCost = 3, IsWeapon = true } },
{ "Unleash the Hounds", new CardData { ManaCost = 3 , Aoe = true} },
{ "Unlicensed Apothecary", new CardData { ManaCost = 3 } },
{ "Unstable Evolution", new CardData { ManaCost = 1 } },
{ "Upgrade!", new CardData { ManaCost = 1, IsWeapon = true } },
{ "Uther of the Ebon Blade", new CardData { ManaCost = 9 } },
{ "Val'anyr", new CardData { ManaCost = 6, IsWeapon = true } },
{ "Valeera the Hollow", new CardData { ManaCost = 9 } },
{ "Vanish", new CardData { ManaCost = 6, Aoe = true } },
{ "Vilefin Inquisitor", new CardData { ManaCost = 1 } },
{ "Vilespine Slayer", new CardData { ManaCost = 5, IsRemoval = true } },
{ "Vinecleaver", new CardData { ManaCost = 7, IsWeapon = true } },
{ "Violent Teacher", new CardData { ManaCost = 4 } },
{ "Viscious Fledgling", new CardData { ManaCost = 3 } },
{ "Voidlord", new CardData { ManaCost = 9 } },
{ "Voidwalker", new CardData { ManaCost = 1,  Attack = 1, Health = 3} },
{ "Volcano", new CardData { ManaCost = 5, Aoe = true } },
{ "Vulgar Homunculus", new CardData { ManaCost = 2 } },
{ "Wandering Monster", new CardData { ManaCost = 2, IsSecret = true } },
{ "Wax Elemental", new CardData { ManaCost = 1 } },
{ "Whirlwind", new CardData { ManaCost = 1 , Aoe = true} },
{ "Wild Growth", new CardData { ManaCost = 3 } },
{ "Wild Pyromancer", new CardData { ManaCost = 2, Aoe = true } },
{ "Youthful Brewmaster", new CardData { ManaCost = 2 } },
{ "Ysera", new CardData { ManaCost = 9 } },
{ "Y'Shaarj Rage Unbound", new CardData { ManaCost = 10 } },
{ "Zola the Gorgon", new CardData { ManaCost = 3 } },
 {"Acherus Veteran", new CardData { ManaCost = 1 } },
 {"Acidic Swap Ooze", new CardData { ManaCost = 2, IsWeaponRemoval = true } },
 {"Al'Akir the Windlord", new CardData { ManaCost = 8 } },
 {"Amani Berserker", new CardData { ManaCost = 2 } },
 {"Arcane Keysmith", new CardData { ManaCost = 4 } },
 {"Arcane Missiles", new CardData { ManaCost = 1 } },
 {"Arcane Shot", new CardData { ManaCost = 1, IsBurn = true } },
 {"Arcane Tyrant", new CardData { ManaCost = 5 } },
 {"Archbishop Benedictus", new CardData { ManaCost = 7 } },
 {"Argent Commander", new CardData { ManaCost = 6 } },
 {"Argent Protector", new CardData { ManaCost = 2 } },
 {"Armani Berserker", new CardData { ManaCost = 0 } },
 {"Avenging Wrath", new CardData { ManaCost = 6 } },
 {"Awaken the Makers", new CardData { ManaCost = 1 } },
 {"Baku the Mooneater", new CardData { ManaCost = 9 } },
 {"Baleful Banker", new CardData { ManaCost = 2 } },
 {"Baron Geddon", new CardData { ManaCost = 7 } },
 {"Blessing of Kings", new CardData { ManaCost = 4, Attack = 4, Health = 4 } },
 {"Blessing of Might", new CardData { ManaCost = 1 } },
 {"Blink Fox", new CardData { ManaCost = 3 } },
 {"Bloodmage Thalnos", new CardData { ManaCost = 2 } },
 {"Bone Drake", new CardData { ManaCost = 6 } },
 {"Charged Devilsaur", new CardData { ManaCost = 8 } },
 {"Chillblade Champion", new CardData { ManaCost = 4 } },
 {"Cinderstorm", new CardData { ManaCost = 3 } },
 {"Circle of Healing", new CardData { ManaCost = 0 } },
 {"Cornered Sentry", new CardData { ManaCost = 2 } },
 {"Corpsetaker", new CardData { ManaCost = 4 } },
 {"Crypt Lord", new CardData { ManaCost = 3 } },
 {"Crystalline Oracle", new CardData { ManaCost = 1 } },
 {"Darius Crowley", new CardData { ManaCost = 5 } },
 {"Dark Iron Dwarf", new CardData { ManaCost = 4 } },
 {"Divine Hymn", new CardData { ManaCost = 2 } },
 {"Dread Infernal", new CardData { ManaCost = 6 } },
 {"Druid of the Scythe", new CardData { ManaCost = 3 } },
 {"Earthen Might", new CardData { ManaCost = 1 } },
 {"Evolving Spores", new CardData { ManaCost = 4 } },
 {"Far Sight", new CardData { ManaCost = 3 } },
 {"Ferocious Howl", new CardData { ManaCost = 3 } },
 {"Fire Elemental", new CardData { ManaCost = 6 } },
 {"Fire Plume's Heart", new CardData { ManaCost = 1 } },
 {"Forge Of Souls", new CardData { ManaCost = 2 } },
 {"Gather Your Party", new CardData { ManaCost = 6 } },
 {"Genn Greymane", new CardData { ManaCost = 6 } },
 {"Geosculptor Yip", new CardData { ManaCost = 8 } },
 {"Gluttonous Ooze", new CardData { ManaCost = 3 } },
 {"Gnomeferatu", new CardData { ManaCost = 2 } },
 {"Grievous Bite", new CardData { ManaCost = 2 } },
 {"Grommash Hellscream", new CardData { ManaCost = 8 } },
 {"Hadronox", new CardData { ManaCost = 9 } },
 {"Hagatha the Witch", new CardData { ManaCost = 8, Aoe = true } },
 {"Hallucination", new CardData { ManaCost = 1 } },
 {"Hammer of Wrath", new CardData { ManaCost = 4 } },
 {"Hench-Clan Thug", new CardData { ManaCost = 3 } },
 {"Holy Fire", new CardData { ManaCost = 6, IsBurn = true } },
 {"Hooked Reaver", new CardData { ManaCost = 4 } },
 {"Injured Blademaster", new CardData { ManaCost = 3 } },
 {"Iron Hide", new CardData { ManaCost = 1 } },
 {"Ironbeak Owl", new CardData { ManaCost = 3 } },
 {"Ironwood Golem", new CardData { ManaCost = 4 } },
 {"Kalimos Primal Lord", new CardData { ManaCost = 8 } },
 {"Kathrena Winterwisp", new CardData { ManaCost = 8 } },
 {"King Krush", new CardData { ManaCost = 9 } },
 {"Knife Jugger", new CardData { ManaCost = 2 } },
 {"Lifedrinker", new CardData { ManaCost = 4 } },
 {"Lightning Bolt", new CardData { ManaCost = 1 } },
 {"Lightning Storm", new CardData { ManaCost = 3, Aoe = true } },
 {"Lord Godfrey", new CardData { ManaCost = 7 } },
 {"Lyra the Sunshard", new CardData { ManaCost = 5 } },
 {"Moonfire", new CardData { ManaCost = 0 } },
 {"Mossy Horror", new CardData { ManaCost = 6 } },
 {"Murkspark Eel", new CardData { ManaCost = 2 } },
 {"Naturalize", new CardData { ManaCost = 1 } },
 {"Nightmare Amalgam", new CardData { ManaCost = 4 } },
 {"Phantom Militia", new CardData { ManaCost = 3 } },
 {"Play Dead", new CardData { ManaCost = 1 } },
 {"Primalfin Totem", new CardData { ManaCost = 2 } },
 {"Rabid Worgen", new CardData { ManaCost = 3 } },
 {"Radient Elemental", new CardData { ManaCost = 2 } },
 {"Raid Leader", new CardData { ManaCost = 3 } },
 {"Reckless Flurry", new CardData { ManaCost = 3, Aoe = true } },
 {"Rotface", new CardData { ManaCost = 8 } },
 {"Rotten Applebaum", new CardData { ManaCost = 5 } },
 {"Sandbinder", new CardData { ManaCost = 4 } },
 {"Saronite Chain Gang", new CardData { ManaCost = 4 } },
 {"Savannah Highmane", new CardData { ManaCost = 6 } },
 {"Sea Giant", new CardData { ManaCost = 10 } },
 {"Shroom Brewer", new CardData { ManaCost = 4 } },
 {"Shudderwock", new CardData { ManaCost = 9 } },
 {"Silence", new CardData { ManaCost = 0 } },
 {"Silver Vanguard", new CardData { ManaCost = 7 } },
 {"Sindragosa", new CardData { ManaCost = 8 } },
 {"Snipe", new CardData { ManaCost = 2, IsSecret = true } },
 {"Soul of the Forest", new CardData { ManaCost = 4 } },
 {"Spiritsinger Umbra", new CardData { ManaCost = 4 } },
 {"Starfall", new CardData { ManaCost = 5, Aoe = true } },
 {"Stitched Tracker", new CardData { ManaCost = 3 } },
 {"Stormwind Champion", new CardData { ManaCost = 7 } },
 {"Sunfury Protector", new CardData { ManaCost = 2 } },
 {"The Glass Knight", new CardData { ManaCost = 4 } },
 {"Tinkmaster Overspark", new CardData { ManaCost = 3 } },
 {"To My Side!", new CardData { ManaCost = 6 } },
 {"Tortollan Shellraiser", new CardData { ManaCost = 4 } },
 {"Town Crier", new CardData { ManaCost = 1 } },
 {"Truesilver Champion", new CardData { ManaCost = 4, IsWeapon = true } },
 {"Twig Of The World Tree", new CardData { ManaCost = 4, IsWeapon = true } },
 {"Twillight's Call", new CardData { ManaCost = 3 } },
 {"Unpowered Steambot", new CardData { ManaCost = 4 } },
 {"Vicious Fledgling", new CardData { ManaCost = 3 } },
 {"Vicious Scalehide", new CardData { ManaCost = 2 } },
 {"Violet Teacher", new CardData { ManaCost = 4 } },
 {"Scalelord", new CardData { ManaCost = 5 } },
 {"Voodoo Doll", new CardData { ManaCost = 3, IsRemoval = true } },
 {"Warpath", new CardData { ManaCost = 2, Aoe = true } },
 {"Wing Blast", new CardData { ManaCost = 4 } },
 {"Wispering Woods", new CardData { ManaCost = 4 } },
 {"Witching Hour", new CardData { ManaCost = 3 } },
 {"Witch's Cauldron", new CardData { ManaCost = 3 } },
 {"Witchwood Piper", new CardData { ManaCost = 4 } },
 {"Woecleaver", new CardData { ManaCost = 8, IsWeapon = true } },
 {"Wolfrider", new CardData { ManaCost = 3 } },
 {"Woodcutter's Axe", new CardData { ManaCost = 2, IsWeapon = true } },
 {"Wrath", new CardData { ManaCost = 2 } },
 { "Academic Espionage", new CardData { ManaCost = 4 } },
 { "Arcane Dynamo", new CardData { ManaCost = 6 } },
 { "Arcane Intelect", new CardData { ManaCost = 3 } },
 { "Astromancer", new CardData { ManaCost = 7 } },
 { "Astromancer Solarian", new CardData { ManaCost = 3, Attack = 3, Health = 2 } },
 { "Augmented Elekk", new CardData { ManaCost = 3 } },
 { "Azalina Soulthief", new CardData { ManaCost = 7 } },
 { "Barkskin", new CardData { ManaCost = 1 } },
 { "Beryllium Nullifier", new CardData { ManaCost = 7 } },
 { "Big Game Hunter", new CardData { ManaCost = 5 } },
 { "Binding Heal", new CardData { ManaCost = 1 } },
 { "Biology Project", new CardData { ManaCost = 1 } },
 { "Blade Flurry", new CardData { ManaCost = 2, Aoe = true } },
 { "Blightnozzle Crawler", new CardData { ManaCost = 4 } },
 { "Bloodbloom", new CardData { ManaCost = 2 } },
 { "Bull Dozer", new CardData { ManaCost = 9 } },
 { "Cataclysm", new CardData { ManaCost = 4 } },
 { "Celestial Emissary", new CardData { ManaCost = 2 } },
 { "Coffin Crasher", new CardData { ManaCost = 6 } },
 { "Colbalt Scalebane", new CardData { ManaCost = 5 } },
 { "Cosmic Anomaly", new CardData { ManaCost = 4 } },
 { "Damaged Stegotron", new CardData { ManaCost = 6 } },
 { "Dead Ringer", new CardData { ManaCost = 2 } },
 { "Demonic Project", new CardData { ManaCost = 2 } },
 { "Dendrologist", new CardData { ManaCost = 2 } },
 { "Devilsaur Egg", new CardData { ManaCost = 3 } },
 { "Direhorn Hatchling", new CardData { ManaCost = 5 } },
 { "Dr. Boom, Mad Genius", new CardData { ManaCost = 9 } },
 { "Dreampetal Florist", new CardData { ManaCost = 7 } },
 { "Dyn-o-matic", new CardData { ManaCost = 5 } },
 { "Earth Shock", new CardData { ManaCost = 1 } },
 { "Electra Stormsurge", new CardData { ManaCost = 3 } },
 { "Eternium Rover", new CardData { ManaCost = 1 } },
 { "Fireworks Tech", new CardData { ManaCost = 2 } },
 { "Flobbidinous Floop", new CardData { ManaCost = 4 } },
 { "Floop's Glorious Gloop", new CardData { ManaCost = 1 } },
 { "Fungal Enchanter", new CardData { ManaCost = 5 } },
 { "Galvanizer", new CardData { ManaCost = 2 } },
 { "Giggling Inventor", new CardData { ManaCost = 5 } },
 { "Gloop Sprayer", new CardData { ManaCost = 8 } },
 { "Glow-Tron", new CardData { ManaCost = 1 } },
 { "Gorehowl", new CardData { ManaCost = 7, IsWeapon = true } },
 { "Happy Ghoul", new CardData { ManaCost = 3 } },
 { "Houndmaster Shaw", new CardData { ManaCost = 4 } },
 { "Juicy Psychmelon", new CardData { ManaCost = 4 } },
 { "King Mosh", new CardData { ManaCost = 9 } },
 { "King Togwaggle", new CardData { ManaCost = 8 } },
 { "Lab Recruiter", new CardData { ManaCost = 2 } },
 { "Landscaping", new CardData { ManaCost = 3 } },
 { "Lightwarden", new CardData { ManaCost = 1 } },
 { "Imprisoned Sungill", new CardData { ManaCost = 1 } },
 { "Lorewalker Cho", new CardData { ManaCost = 2 } },
 { "Luna's Pocket Galaxy", new CardData { ManaCost = 7 } },
 { "Mechanical Whelp", new CardData { ManaCost = 6 } },
 { "Mecharoo", new CardData { ManaCost = 1 } },
 { "Mecha'thun", new CardData { ManaCost = 10 } },
 { "Menacing Nimbus", new CardData { ManaCost = 2 } },
 { "Mirror Image", new CardData { ManaCost = 1 } },
 { "Mulchmuncher", new CardData { ManaCost = 10 } },
 { "Myra's Unstable Element", new CardData { ManaCost = 5 } },
 { "Necrium Blade", new CardData { ManaCost = 3, IsWeapon = true } },
 { "Necrium Vial", new CardData { ManaCost = 5 } },
 { "Omega Assembly", new CardData { ManaCost = 1 } },
 { "Pogo-Hopper", new CardData { ManaCost = 2 } },
 { "Professor Putricide", new CardData { ManaCost = 4 } },
 { "Rat Trap", new CardData { ManaCost = 2, IsSecret = true } },
 { "Reckless Experimenter", new CardData { ManaCost = 5 } },
 { "Sacrificial Pact", new CardData { ManaCost = 0 } },
 { "Shadowflame", new CardData { ManaCost = 4 } },
 { "Shooting Star", new CardData { ManaCost = 1 } },
 { "Soul Infusion", new CardData { ManaCost = 1 } },
 { "Spider Bomb", new CardData { ManaCost = 3 } },
 { "Sprint", new CardData { ManaCost = 7 } },
 { "Stargazer Luna", new CardData { ManaCost = 3 } },
 { "Storm Chaser", new CardData { ManaCost = 4 } },
 { "Stormforged Axe", new CardData { ManaCost = 2 } },
 { "Subject 9", new CardData { ManaCost = 5 } },
 { "Terrorscale Stalker", new CardData { ManaCost = 3 } },
 { "Test Subject", new CardData { ManaCost = 1 } },
 { "The Black Knight", new CardData { ManaCost = 6 } },
 { "The Boomship", new CardData { ManaCost = 9 } },
 { "The Runespear", new CardData { ManaCost = 8 } },
 { "The Soularium", new CardData { ManaCost = 1 } },
 { "Thunderhead", new CardData { ManaCost = 4 } },
 { "Ticking Abomination", new CardData { ManaCost = 4 } },
 { "Topsy Turvy", new CardData { ManaCost = 0 } },
 { "Toxicologist", new CardData { ManaCost = 2 } },
 { "Twilight's Call", new CardData { ManaCost = 3 } },
 { "Tyrantus", new CardData { ManaCost = 10 } },
 { "Vivid Nightmare", new CardData { ManaCost = 3 } },
 { "Void Ripper", new CardData { ManaCost = 3 } },
 { "Voodoo Doctor", new CardData { ManaCost = 1 } },
 { "Wargear", new CardData { ManaCost = 5 } },
 { "Weapons Project", new CardData { ManaCost = 2, IsWeapon = true } },
 { "Zap!", new CardData { ManaCost = 0 } },
 { "Zilliax", new CardData { ManaCost = 5 } },
 {"Amani War Bear", new CardData{ManaCost = 7} },
 {"Ancient Brewmaster", new CardData{ManaCost = 4} },
 {"Bloodscalp Strategist", new CardData{ManaCost = 3} },
 {"Charged Devisaur", new CardData{ManaCost = 8} },
 {"Crowd Roaster", new CardData{ManaCost = 7} },
 {"Crystallizer", new CardData{ManaCost = 1} },
 {"Crystalsmith Kangor", new CardData{ManaCost = 2} },
 {"Dire Frenzy", new CardData{ManaCost = 4} },
 {"Dragonmaw Scorcher", new CardData{ManaCost = 5} },
 {"Emberscale Drake", new CardData{ManaCost = 5} },
 {"Firetree Witchdoctor", new CardData{ManaCost = 2} },
 {"Flash of Light", new CardData{ManaCost = 2} },
 {"Guilded Gargoyle", new CardData{ManaCost = 2} },
 {"Lynessa Sunsorrow", new CardData{ManaCost = 7} },
 {"Masked Contender", new CardData{ManaCost = 3} },
 {"Mass Hysteria", new CardData{ManaCost = 5, Aoe = true} },
 {"Master's Call", new CardData{ManaCost = 3} },
 {"Mojomaster Zihi", new CardData{ManaCost = 6} },
 {"Nerubian Unraveler", new CardData{ManaCost = 6} },
 {"Oondasta", new CardData{ManaCost = 9} },
 {"Scaleworm", new CardData{ManaCost = 4} },
 {"Scarab Egg", new CardData{ManaCost = 2} },
 {"Secret Plan", new CardData{ManaCost = 1} },
 {"Secretkeeper", new CardData{ManaCost = 1} },
 {"Shirvallah, the Tiger", new CardData{ManaCost = 25} },
 {"Smolderthorn Lancer", new CardData{ManaCost = 3} },
 {"Snake Trap", new CardData{ManaCost = 2, IsSecret = true} },
 {"Soup Vendor", new CardData{ManaCost = 2} },
 {"Springpaw", new CardData{ManaCost = 1} },
 {"Supercollider", new CardData{ManaCost = 7, IsWeapon=true} },
 {"Timber Wolf", new CardData{ManaCost = 1} },
 {"Time Out!", new CardData{ManaCost = 3} },
 {"Tundra Rhino", new CardData{ManaCost = 5} },
 {"Venomstrike Trap", new CardData{ManaCost = 2, IsSecret=true} },
 {"Witchwood Grizzly", new CardData{ManaCost = 5} },
 {"Zerek's Cloning Gallery", new CardData{ManaCost = 9} },
 {"Zul'jin", new CardData{ManaCost = 10} },
 { "Annoy-o-Module", new CardData { ManaCost = 4 } },
 { "Astral Tiger", new CardData { ManaCost = 4 } },
 { "Banana Buffoon", new CardData { ManaCost = 3 } },
 { "Black Cat", new CardData { ManaCost = 3 } },
 { "Blast Wave", new CardData { ManaCost = 5 } },
 { "Crystology", new CardData { ManaCost = 2 } },
 { "Cutthroat Buccaneer", new CardData { ManaCost = 3 } },
 { "Da Undatakah", new CardData { ManaCost = 8 } },
 { "Daring Fire-Eater", new CardData { ManaCost = 1 } },
 { "Doomhammer", new CardData { ManaCost = 5, IsWeapon = true } },
 { "Doubling Imp", new CardData { ManaCost = 3 } },
 { "Flobbidnous Floop", new CardData { ManaCost = 4 } },
 { "Force of Nature", new CardData { ManaCost = 5 } },
 { "Grim Rally", new CardData { ManaCost = 1 } },
 { "Half-Time Scavenger", new CardData { ManaCost = 4 } },
 { "Ironwwod Golem", new CardData { ManaCost = 4 } },
 { "Jan'alai, the Dragonhawk", new CardData { ManaCost = 7 } },
 { "Kangor's Endless Army", new CardData { ManaCost = 7 } },
 { "Lava Burst", new CardData { ManaCost = 3, IsBurn = true } },
 { "Lay on Hands", new CardData { ManaCost = 8 } },
 { "Likkim", new CardData { ManaCost = 2, IsWeapon = true } },
 { "Mana Addict", new CardData { ManaCost = 2 } },
 { "Meat Wagon", new CardData { ManaCost = 4 } },
 { "Mechano-Egg", new CardData { ManaCost = 5 } },
 { "Mosh'Ogg Enforcer", new CardData { ManaCost = 8 } },
 { "Princess Talanji", new CardData { ManaCost = 8 } },
 { "Pyromaniac", new CardData { ManaCost = 3 } },
 { "Raiding Party", new CardData { ManaCost = 3 } },
 { "Research Project", new CardData { ManaCost = 2 } },
 { "Rockbiter Weapon", new CardData { ManaCost = 1 } },
 { "Saronite Taskmaster", new CardData { ManaCost = 1 } },
 { "Shrink Ray", new CardData { ManaCost = 5 } },
 { "Spellzerker", new CardData { ManaCost = 2 } },
 { "Spirit of the Frog", new CardData { ManaCost = 3 } },
 { "Spirit of the Shark", new CardData { ManaCost = 4 } },
 { "Stormwatcher", new CardData { ManaCost = 7 } },
 { "Tome of Intellect", new CardData { ManaCost = 1 } },
 { "Totemic Smash", new CardData { ManaCost = 1, IsRemoval = true } },
 { "Treespeaker", new CardData { ManaCost = 5 } },
 { "Twig of the World Tree", new CardData { ManaCost = 4 } },
 { "Unbound Elemental", new CardData { ManaCost = 3 } },
 { "Voltaic Burst", new CardData { ManaCost = 1 } },
 { "Wardruid Loti", new CardData { ManaCost = 3 } },
 { "Zentimo", new CardData { ManaCost = 3 } },
 {"Extra Arms", new CardData { ManaCost = 3 } },
 {"Grave Horror", new CardData { ManaCost = 0 } },
 {"Sand Drudge", new CardData { ManaCost = 0 } },
 {"Seance", new CardData { ManaCost = 2 } },
 {"Autodefense Matrix", new CardData { ManaCost = 1 , IsSecret = true} },
 {"Bellringer Sentry", new CardData { ManaCost = 4 } },
 {"Bonemare", new CardData { ManaCost = 8 } },
 {"Cairne Bloodhoof", new CardData { ManaCost = 6 } },
 {"Captain Hooktusk", new CardData { ManaCost = 8 } },
 {"Clockwork Automation", new CardData { ManaCost = 5 } },
 {"Evasion", new CardData { ManaCost = 2, IsSecret = true } },
 {"Grave Shambler", new CardData { ManaCost = 4 } },
 {"Hakkar the Soulflayer", new CardData { ManaCost = 10 } },
 {"Holy Wrath", new CardData { ManaCost = 5 } },
 {"Kobold Illusionist", new CardData { ManaCost = 3 } },
 {"Noble Sacrifice", new CardData { ManaCost = 1, IsSecret = true } },
 {"Potion of Heroism", new CardData { ManaCost = 2 } },
 {"Pounce", new CardData { ManaCost = 0 } },
 {"Prismatic Lens", new CardData { ManaCost = 4 } },
 {"Razorpetal Volley", new CardData { ManaCost = 2 } },
 {"Redemption", new CardData { ManaCost = 1, IsSecret = true } },
 {"Misdirection", new CardData { ManaCost = 2, IsSecret = true } },
 {"Revenge of the Wild", new CardData { ManaCost = 2 } },
 {"Role the Bones", new CardData { ManaCost = 2 } },
 {"Shadowblade", new CardData { ManaCost = 3, IsWeapon = true } },
 {"Sharkfin Fan", new CardData { ManaCost = 2 } },
 {"Shirvallah the Tiger", new CardData { ManaCost = 25 } },
 {"Sinister Strike", new CardData { ManaCost = 1, IsBurn = true } },
 {"Ticket Scalper", new CardData { ManaCost = 5 } },
 {"Windfury Harpy", new CardData { ManaCost = 6 } },
 {"Bog Slosher", new CardData { ManaCost = 3 } },
 {"Countess Ashmore", new CardData { ManaCost = 7 } },
 {"Elementary Reaction", new CardData { ManaCost = 2 } },
 {"Fire Plume Harbinger", new CardData { ManaCost = 2 } },
 {"Fire Plume Pheonix", new CardData { ManaCost = 4 } },
 {"Frothing Beserker", new CardData { ManaCost = 3 } },
 {"Militia Commander", new CardData { ManaCost = 4 } },
 {"Shadow Madness", new CardData { ManaCost = 4 } },
 {"Tol'vir Stoneshaper", new CardData { ManaCost = 4 } },
 { "Soulwarden", new CardData { ManaCost = 6 } },
  { "Headhunter's Hatchet", new CardData { ManaCost = 2, IsWeapon = true } },
   {"Swamp Dragon Egg", new CardData { ManaCost = 1 } },
 {"Bwonsamdi the Dead", new CardData { ManaCost = 0 } },

 {"Abusive Sergeant", new CardData { ManaCost = 1 } },
 {"Acornbearer", new CardData { ManaCost = 1 } },
 {"Ancestral Spirit", new CardData { ManaCost = 2 } },
 {"Ancient Watcher", new CardData { ManaCost = 2 } },
 {"Arcane Watcher", new CardData { ManaCost = 3 } },
 {"Archivist Elysiana", new CardData { ManaCost = 8 } },
 {"Archmage Vargoth", new CardData { ManaCost = 4,  Attack = 2, Health = 6 } },
 {"Arch-Villain Rafaam", new CardData { ManaCost = 7 } },
 {"Auchenai Phantasm", new CardData { ManaCost = 2 } },
 {"Auchenai Soulpriest", new CardData { ManaCost = 4 } },
 {"Baited Arrow", new CardData { ManaCost = 5, IsBurn = true } },
 {"Big Bad Voodoo", new CardData { ManaCost = 2 } },
 {"Blastmaster Boom", new CardData { ManaCost = 7 } },
 {"Blessing of the Ancients", new CardData { ManaCost = 3 } },
 {"Bomb Toss", new CardData { ManaCost = 2 } },
 {"Book of Specters", new CardData { ManaCost = 2 } },
 {"Boommaster Flark", new CardData { ManaCost = 7 } },
 {"Bronze Gatekeeper", new CardData { ManaCost = 3 } },
 {"Bronze Herald", new CardData { ManaCost = 3 } },
 {"Cathedral Gargoyle", new CardData { ManaCost = 2 } },
 {"Catrina Muerte", new CardData { ManaCost = 8 } },
 {"Chameleos", new CardData { ManaCost = 1 } },
 {"Clockwork Goblin", new CardData { ManaCost = 3 } },
 {"Commander Rhyssa", new CardData { ManaCost = 3 } },
 {"Conjurer's Calling", new CardData { ManaCost = 3 } },
 {"Convincing Infiltrator", new CardData { ManaCost = 5 } },
 {"Crystalsong Portal", new CardData { ManaCost = 2 } },
 {"Dalaran Librarian", new CardData { ManaCost = 2 } },
 {"Desperate Measures", new CardData { ManaCost = 1 } },
 {"Dragon Roar", new CardData { ManaCost = 2 } },
 {"Dreamway Guardians", new CardData { ManaCost = 2 } },
 {"Eureka!", new CardData { ManaCost = 6 } },
 {"EVIL Cable Rat", new CardData { ManaCost = 2 } },
 {"EVIL Conscripter", new CardData { ManaCost = 2 } },
 {"EVIL Genius", new CardData { ManaCost = 2 } },
 {"EVIL Miscreant", new CardData { ManaCost = 3, Attack = 1, Health = 4 } },
 {"Explodinator", new CardData { ManaCost = 4 } },
 {"Face Collector", new CardData { ManaCost = 3 } },
 {"Faceless Rager", new CardData { ManaCost = 3 } },
 {"Forbidden Words", new CardData { ManaCost = 0 } },
 {"Grimscale Oracle", new CardData { ManaCost = 1 } },
 {"Hagatha's Scheme", new CardData { ManaCost = 5 } },
 {"Hecklebot", new CardData { ManaCost = 4 } },
 {"Heistbaron Togwaggle", new CardData { ManaCost = 6 } },
 {"Hench-Clan Burglar", new CardData { ManaCost = 4 } },
 {"Hench-Clan Hogsteed", new CardData { ManaCost = 2 } },
 {"Hench-Clan Shadequill", new CardData { ManaCost = 4 } },
 {"Hidden Wisdom", new CardData { ManaCost = 1 } },
 {"Holy Nova", new CardData { ManaCost = 5 } },
 {"Jepetto Joybuzz", new CardData { ManaCost = 8 } },
 {"Keeper Stalladris", new CardData { ManaCost = 2 } },
 {"Khadgar", new CardData { ManaCost = 2 } },
 {"Madame Lazul", new CardData { ManaCost = 3, Attack = 3, Health = 2 } },
 {"Magic Carpet", new CardData { ManaCost = 3 } },
 {"Mark of the Loa", new CardData { ManaCost = 4 } },
 {"Marked Shot", new CardData { ManaCost = 4 } },
 {"Mass Resurrection", new CardData { ManaCost = 9 } },
 {"Missile Launcher", new CardData { ManaCost = 6 } },
 {"Muckmorpher", new CardData { ManaCost = 5 } },
 {"Murloc Tastyfin", new CardData { ManaCost = 4 } },
 {"Murloc Tidehunter", new CardData { ManaCost = 2 } },
 {"Mysterious Blade", new CardData { ManaCost = 2, IsWeapon = true } },
 {"Never Surrender!", new CardData { ManaCost = 1,  IsSecret = true } },
 {"Omega Devastator", new CardData { ManaCost = 4 } },
 {"Onyxia", new CardData { ManaCost = 9 } },
 {"Pilfer", new CardData { ManaCost = 1 } },
 {"Power of Creation", new CardData { ManaCost = 8 } },
 {"Quartz Elemental", new CardData { ManaCost = 5 } },
 {"Rabble Bouncer", new CardData { ManaCost = 7 } },
 {"Rapid Fire", new CardData { ManaCost = 1 } },
 {"Replicating Menace", new CardData { ManaCost = 4 } },
 {"Scargil", new CardData { ManaCost = 4 } },
 {"Shadow Word: Pain", new CardData { ManaCost = 2 } },
 {"Shimmerfly", new CardData { ManaCost = 1 } },
 {"Sludge Slurper", new CardData { ManaCost = 1 } },
 {"Soul of the Murloc", new CardData { ManaCost = 2 } },
 {"Spectral Cutlass", new CardData { ManaCost = 4 } },
 {"Sunreaver Spy", new CardData { ManaCost = 2 } },
 {"Tess Greymane", new CardData { ManaCost = 8 } },
 {"The Forest's Aid", new CardData { ManaCost = 8 } },
 {"Thoughtsteal", new CardData { ManaCost = 3 } },
 {"Toxfin", new CardData { ManaCost = 1 } },
 {"Underbelly Angler", new CardData { ManaCost = 2 } },
 {"Underbelly Fence", new CardData { ManaCost = 2 } },
 {"Unleash the Beast", new CardData { ManaCost = 6 } },
 {"Unseen Saboteur", new CardData { ManaCost = 6 } },
 {"Unsleeping Soul", new CardData { ManaCost = 4 } },
 {"Ursatron", new CardData { ManaCost = 3 } },
 {"Vendetta", new CardData { ManaCost = 4 } },
 {"Venomizer", new CardData { ManaCost = 2 } },
 {"Vereesa Windrunner", new CardData { ManaCost = 7 } },
 {"Waggle Pick", new CardData { ManaCost = 4, IsWeapon = true } },
 {"Walk the Plank", new CardData { ManaCost = 4 } },
 {"Walking Fountain", new CardData { ManaCost = 8 } },
 {"Wrenchcalibur", new CardData { ManaCost = 4, IsWeapon = true } },
  {"Kalecgos", new CardData { ManaCost = 10 } },
 {"Batterhead", new CardData { ManaCost = 8 } },
 {"Call to Adventure", new CardData { ManaCost = 3 } },
 {"Chef Nomi", new CardData { ManaCost = 7 } },
 {"Crystal Power", new CardData { ManaCost = 1 } },
 {"Duel!", new CardData { ManaCost = 5 } },
 {"Elemental Evocation", new CardData { ManaCost = 0 } },
 {"Harvest Golem", new CardData { ManaCost = 3 } },
 {"Haunting Visions", new CardData { ManaCost = 3 } },
 {"Krag'wa, the Frog", new CardData { ManaCost = 6 } },
 {"Lazul's Scheme", new CardData { ManaCost = 0 } },
 {"Lightforged Blessing", new CardData { ManaCost = 2 } },
 {"Magic Trick", new CardData { ManaCost = 1 } },
 {"Mana Cyclone", new CardData { ManaCost = 2 } },
 {"Questing Adventurer", new CardData { ManaCost = 3, Attack = 2, Health = 2 } },
 {"Rain of Toads", new CardData { ManaCost = 6 } },
 {"Ray of Frost", new CardData { ManaCost = 1 } },
 {"Regenerate", new CardData { ManaCost = 0 } },
 {"Starfire", new CardData { ManaCost = 0 } },
 {"Sunreaver Warmage", new CardData { ManaCost = 5 } },
 {"Swampqueen Hagatha", new CardData { ManaCost = 7 } },
 {"Witch's Brew", new CardData { ManaCost = 2 } },
 { "Messenger Raven", new CardData { ManaCost = 3 } },

 {"Archmage Arugal", new CardData { ManaCost = 2 } },
 {"Barista Lynchen", new CardData { ManaCost = 5 } },
 {"Bloodsail Corsair", new CardData { ManaCost = 1 } },
 {"Devastate", new CardData { ManaCost = 1 } },
 {"Earthen Ring Farseer", new CardData { ManaCost = 3 } },
 {"Feral Spirit", new CardData { ManaCost = 3 } },
 {"Inner Rage", new CardData { ManaCost = 0 } },
 {"Marsh Drake", new CardData { ManaCost = 3 } },
 {"Ravencaller", new CardData { ManaCost = 2 } },
 {"Togwaggle's Scheme", new CardData { ManaCost = 1 } },

  {"Ancestral Healing", new CardData { ManaCost = 0 } },
 {"Ancient of Lore", new CardData { ManaCost = 7 } },
 {"Big Bad Archmage", new CardData { ManaCost = 0 } },
 {"Coppertail Imposter", new CardData { ManaCost = 0 } },
 {"Daring Escape", new CardData { ManaCost = 0 } },
 {"Defender of Argus", new CardData { ManaCost = 4 } },
 {"Elven Archer", new CardData { ManaCost = 1 } },
 {"Faerie Dragon", new CardData { ManaCost = 2 } },
 {"Glowstone Technician", new CardData { ManaCost = 5 } },
 {"Healing Touch", new CardData { ManaCost = 0 } },
 {"Hench-Clan Hag", new CardData { ManaCost = 0 } },
 {"Lucentbark", new CardData { ManaCost = 0 } },
 {"Microtech Controller", new CardData { ManaCost = 0 } },
 {"Necromechanic", new CardData { ManaCost = 0 } },
 {"Nine Lives", new CardData { ManaCost = 0 } },
 {"Oblivitron", new CardData { ManaCost = 0 } },
 {"Predatory Instincts", new CardData { ManaCost = 0 } },
 {"Skaterbot", new CardData { ManaCost = 1 } },
 {"SN1P-SN4P", new CardData { ManaCost = 3 } },
 {"Tak Nozwhisker", new CardData { ManaCost = 0 } },
 {"Upgradeable Framebot", new CardData { ManaCost = 2 } },
 {"Vex Crow", new CardData { ManaCost = 4 } },
 {"WANTED!", new CardData { ManaCost = 0 } },
 {"Witchwood Imp", new CardData { ManaCost = 0 } },


{"Activate the Obelisk", new CardData { ManaCost = 1 } },
 {"Ancestral Guardian", new CardData { ManaCost = 0 } },
 {"Ancient Mysteries", new CardData { ManaCost = 0 } },
 {"Ancient of War", new CardData { ManaCost = 0 } },
 {"Anubisath Defender", new CardData { ManaCost = 5 } },
 {"Anubisath Warbringer", new CardData { ManaCost = 9 } },
 {"Aranasi Broodmother", new CardData { ManaCost = 0 } },
 {"Arathi Weaponsmith", new CardData { ManaCost = 0 } },
 {"Arcane Flakmage", new CardData { ManaCost = 2 } },
 {"Armagedillo", new CardData { ManaCost = 6 } },
 {"Armored Goon", new CardData { ManaCost = 6 } },
 {"Armorsmith", new CardData { ManaCost = 1, Attack = 1, Health = 4} },
 {"Battle Rage", new CardData { ManaCost = 2 } },
 {"Bazaar Burglary", new CardData { ManaCost = 1,  } },
 {"Bazaar Mugger", new CardData { ManaCost = 5 } },
 {"BEEEES!!!", new CardData { ManaCost = 3 } },
 {"Blessing of Wisdom", new CardData { ManaCost = 0 } },
 {"Bloodsworn Mercenary", new CardData { ManaCost = 3 } },
 {"Bone Wraith", new CardData { ManaCost = 4 } },
 {"Brightwing", new CardData { ManaCost = 0 } },
 {"Candletaker", new CardData { ManaCost = 3 } },
 {"Cenarius", new CardData { ManaCost = 0 } },
 {"Clever Disguise", new CardData { ManaCost = 2 } },
 {"Cloud Prince", new CardData { ManaCost = 5 } },
 {"Colossus of the Moon", new CardData { ManaCost = 10 } },
 {"Corrupt the Waters", new CardData { ManaCost = 1 } },
 {"Cruel Taskmaster", new CardData { ManaCost = 2 } },
 {"Crystal Merchant", new CardData { ManaCost = 2 } },
 {"Darkest Hour", new CardData { ManaCost = 0 } },
 {"Dinotamer Brann", new CardData { ManaCost = 7 } },
 {"Diseased Vulture", new CardData { ManaCost = 4 } },
 {"Dollmaster Dorian", new CardData { ManaCost = 0 } },
 {"Dr. Morrigan", new CardData { ManaCost = 0 } },
 {"Dune Sculptor", new CardData { ManaCost = 2 } },
 {"Earthquake", new CardData { ManaCost = 7, Aoe = true } },
 {"Elise the Enlightened", new CardData { ManaCost = 5 } },
 {"Ethereal Arcanist", new CardData { ManaCost = 0 } },
 {"EVIL Totem", new CardData { ManaCost = 2 } },
 {"Fel Lord Betrug", new CardData { ManaCost = 7 } },
 {"Fiendish Circle", new CardData { ManaCost = 0 } },
 {"Fishflinger", new CardData { ManaCost = 2 } },
 {"Flame Ward", new CardData { ManaCost = 3, IsSecret = true } },
 {"Frightened Flunky", new CardData { ManaCost = 2 } },
 {"Hack the System", new CardData { ManaCost = 1 } },
 {"Hidden Oasis", new CardData { ManaCost = 6 } },
 {"High Priest Amet", new CardData { ManaCost = 4 } },
 {"Holy Ripple", new CardData { ManaCost = 2, Aoe = true } },
 {"Hooked Scimitar", new CardData { ManaCost = 3, IsWeapon = true,  Attack = 2, Health = 2, Spell = "Combo gain +2"  } },
 {"Trueaim Crescent", new CardData { ManaCost = 1, IsWeapon = true,  Attack = 1, Health = 4, Spell = "After attack minions attack target also"  } },
 {"Hunter's Pack", new CardData { ManaCost = 3 } },
 {"Hyena Alpha", new CardData { ManaCost = 4, Attack = 3, Health = 3, Spell = "summon 2 2/2 if Have secret"  } },
 {"Immortal Prelate", new CardData { ManaCost = 2 } },
 {"Improve Morale", new CardData { ManaCost = 0 } },
 {"Injured Tol'vir", new CardData { ManaCost = 2 } },
 {"Khartut Defender", new CardData { ManaCost = 6 } },
 {"King Phaoris", new CardData { ManaCost = 10 } },
 {"Livewire Lance", new CardData { ManaCost = 3, IsWeapon = true } },
 {"Making Mummies", new CardData { ManaCost = 1 } },
 {"Meteorologist", new CardData { ManaCost = 0 } },
 {"Micro Mummy", new CardData { ManaCost = 2 } },
 {"Mirror Entity", new CardData { ManaCost = 3, IsSecret = true } },
 {"Mogu Fleshshaper", new CardData { ManaCost = 7 } },
 {"Murmy", new CardData { ManaCost = 1 } },
 {"Naga Sand Witch", new CardData { ManaCost = 5 } },
 {"Neferset Ritualist", new CardData { ManaCost = 2 } },
 {"Neferset Thrasher", new CardData { ManaCost = 3 } },
 {"Oasis Surger", new CardData { ManaCost = 5 } },
 {"Penance", new CardData { ManaCost = 2 } },
 {"Pharaoh Cat", new CardData { ManaCost = 1, Attack = 1, Health = 2 } },
 {"Ace Hunter Kreen", new CardData { ManaCost = 3, Attack = 2, Health = 4, Spell = "Others are immune while attacking" } },
 {"Plague of Death", new CardData { ManaCost = 9, Aoe = true } },
 {"Plague of Flames", new CardData { ManaCost = 1, Aoe = true } },
 {"Plague of Murlocs", new CardData { ManaCost = 3 } },
 {"Plague of Wrath", new CardData { ManaCost = 5, Aoe = true } },
 {"Plot Twist", new CardData { ManaCost = 2 } },
 {"Pressure Plate", new CardData { ManaCost = 2, IsSecret = true } },
 {"Psychopomp", new CardData { ManaCost = 4 } },
 {"Puzzle Box of Yogg-Saron", new CardData { ManaCost = 10 } },
 {"Questing Explorer", new CardData { ManaCost = 2 } },
 {"Rafaam's Scheme", new CardData { ManaCost = 1 } },
 {"Rampage", new CardData { ManaCost = 4 } },
 {"Reno the Relicologist", new CardData { ManaCost = 6 } },
 {"Restless Mummy", new CardData { ManaCost = 4 } },
 {"Safeguard", new CardData { ManaCost = 0 } },
 {"Sandhoof Waterbearer", new CardData { ManaCost = 5 } },
 {"Sandstorm Elemental", new CardData { ManaCost = 2 } },
 {"Scarlet Webweaver", new CardData { ManaCost = 6 } },
 {"Serpent Egg", new CardData { ManaCost = 2 } },
 {"Siamat", new CardData { ManaCost = 7 } },
 {"Sir Finley of the Sands", new CardData { ManaCost = 2 } },
 {"Subdue", new CardData { ManaCost = 2 } },
 {"Sul'thraze", new CardData { ManaCost = 0 } },
 {"Supreme Archaeology", new CardData { ManaCost = 1 } },
 {"Swarm of Locusts", new CardData { ManaCost = 6 } },
 {"Temple Berserker", new CardData { ManaCost = 2 } },
 {"Tip the Scales", new CardData { ManaCost = 8 } },
 {"Tomb Warden", new CardData { ManaCost = 8 } },
 {"Tortollan Pilgrim", new CardData { ManaCost = 8 } },
 {"Unseal the Vault", new CardData { ManaCost = 1 } },
 {"Untapped Potential", new CardData { ManaCost = 1 } },
 {"Vessina", new CardData { ManaCost = 4 } },
 {"Vulpera Scoundrel", new CardData { ManaCost = 3, Attack = 2, Health = 3 } },
 {"Wasteland Assassin", new CardData { ManaCost = 5 } },
 {"Weaponized Wasp", new CardData { ManaCost = 3 } },
 {"Wild Bloodstinger", new CardData { ManaCost = 6 } },
 {"Worthy Expedition", new CardData { ManaCost = 1 } },
 {"Zephrys the Great", new CardData { ManaCost = 2,  Attack = 3, Health = 2 } },

 {"Aldor Peacekeeper", new CardData { ManaCost = 3 } },
 {"Anka, the Buried", new CardData { ManaCost = 5 } },
 {"Avenge", new CardData { ManaCost = 1, IsSecret = true } },
 {"Beaming Sidekick", new CardData { ManaCost = 1 } },
 {"Bloodhoof Brave", new CardData { ManaCost = 4 } },
 {"Brazen Zealot", new CardData { ManaCost = 1 } },
 {"Crazed Alchemist", new CardData { ManaCost = 2 } },
 {"Dark Pharaoh Tekahn", new CardData { ManaCost = 5 } },
 {"Desert Hare", new CardData { ManaCost = 3 } },
 {"Desert Spear", new CardData { ManaCost = 3, IsWeapon = true } },
 {"Emperor Thaurissan", new CardData { ManaCost = 6 } },
 {"EVIL Recruiter", new CardData { ManaCost = 3 } },
 {"Expired Merchant", new CardData { ManaCost = 2,  Attack = 2, Health = 1 } },
 {"Flamewaker", new CardData { ManaCost = 3 } },
 {"History Buff", new CardData { ManaCost = 3 } },
 {"Imp Gang Boss", new CardData { ManaCost =  3 } },
 {"Infested Goblin", new CardData { ManaCost = 3 } },
 {"Into the Fray", new CardData { ManaCost = 1 } },
 {"Jar Dealer", new CardData { ManaCost = 1 } },
 {"Lightbomb", new CardData { ManaCost = 6, Aoe = true } },
 {"Mutate", new CardData { ManaCost = 0 } },
 {"Mysterious Challenger", new CardData { ManaCost = 6 } },
 {"N'Zoth, the Corruptor", new CardData { ManaCost = 10 } },
 {"Ragnaros the Firelord", new CardData { ManaCost = 8 } },
 {"Salhet's Pride", new CardData { ManaCost =  3, Attack = 3, Health = 1 } },
 {"Sandwasp Queen", new CardData { ManaCost = 2 } },
 {"Sinister Deal", new CardData { ManaCost = 1 } },
 {"Spirit Bomb", new CardData { ManaCost = 1 } },
 {"Swashburglar", new CardData { ManaCost = 1 } },
 {"Sylvanas Windrunner", new CardData { ManaCost = 6 } },
 {"Thing from Below", new CardData { ManaCost = 5 } },
 {"Varian Wrynn", new CardData { ManaCost = 10 } },

 {"Aeroponics", new CardData { ManaCost = 5,} },
{"Breath of Dreams", new CardData { ManaCost = 2,} },
{"Embiggen", new CardData { ManaCost = 0,} },
{"Emerald Explorer", new CardData { ManaCost = 6,} },
{"Goru the Mightree", new CardData { ManaCost = 7,} },
{"Secure the Deck", new CardData { ManaCost = 1,} },
{"Shrubadier", new CardData { ManaCost = 2,} },
{"Strength in Numbers", new CardData { ManaCost = 1,} },
{"Treenforements", new CardData { ManaCost = 1,} },
{"Ysera Unleashed", new CardData { ManaCost = 9,} },
{"Clear the Way", new CardData { ManaCost = 1,} },
{"Corrosive Breath", new CardData { ManaCost = 2, IsBurn = true} },
{"Diving Gryphon", new CardData { ManaCost = 3,} },
{"Dragonbane", new CardData { ManaCost = 4, Attack = 3, Health = 5 } },
{"Dwarven Sharpshooter", new CardData { ManaCost = 1,Attack = 1, Health = 3 } },
{"Phase Stalker", new CardData { ManaCost = 2, Attack = 2, Health = 3 } },
{"Primordial Explorer", new CardData { ManaCost = 3,} },
{"Stormhammer", new CardData { ManaCost = 3, IsWeapon = true,} },
{"Toxic Reinforcements", new CardData { ManaCost = 1,} },
{"Veranus", new CardData { ManaCost = 6,} },
{"Arcane Breath", new CardData { ManaCost = 1,} },
{"Azure Explorer", new CardData { ManaCost = 4,} },
{"Chenvaala", new CardData { ManaCost = 3,} },
{"Dragoncaster", new CardData { ManaCost = 6,} },
{"Elemental Allies", new CardData { ManaCost = 1,} },
{"Learn Draconic", new CardData { ManaCost = 1,} },
{"Malygos Aspect of Magic", new CardData { ManaCost = 5,} },
{"Mana Giant", new CardData { ManaCost = 8, Attack = 8, Health = 8} },
{"Rolling Fireball", new CardData { ManaCost = 5,} },
{"Violet Spellwing", new CardData { ManaCost = 1,} },
{"Bad Luck Albatross", new CardData { ManaCost = 3,} },
{"Big Ol Welp", new CardData { ManaCost = 5,} },
{"Blazing Battlemage", new CardData { ManaCost = 1,  Attack = 2, Health = 2} },
{"Blowtorch Saboteur", new CardData { ManaCost = 3,} },
{"Camouflaged Dirigible", new CardData { ManaCost = 6,} },
{"Chromatic Egg", new CardData { ManaCost = 5,} },
{"Cobalt Spellkin", new CardData { ManaCost = 5,} },
{"Depth Charge", new CardData { ManaCost = 1,} },
{"Devoted Maniac", new CardData { ManaCost = 4,} },
{"Draconic Lackey", new CardData { ManaCost = 1,} },
{"Dragon Breeder", new CardData { ManaCost = 2,} },
{"Dragonmaw Poacher", new CardData { ManaCost = 4,} },
{"Dragonqueen Alexstrasza", new CardData { ManaCost = 9,} },
{"Dread Raven", new CardData { ManaCost = 3,} },
{"Evasive Chimaera", new CardData { ManaCost = 2,} },
{"Evasive Drakonid", new CardData { ManaCost = 7,} },
{"Evasive Feywing", new CardData { ManaCost = 4,} },
{"Evasive Wyrm", new CardData { ManaCost = 6,} },
{"Faceless Corruptor", new CardData { ManaCost = 5,} },
{"Fire Hawk", new CardData { ManaCost = 3,} },
{"Frizz Kindleroost", new CardData { ManaCost = 4,} },
{"Goboglide Tech", new CardData { ManaCost = 3,} },
{"Grizzled Wizard", new CardData { ManaCost = 2,} },
{"Gyrocopter", new CardData { ManaCost = 6,} },
{"Hippogryph", new CardData { ManaCost = 4,} },
{"Hoard Pillager", new CardData { ManaCost = 4,} },
{"Hot Air Baloon", new CardData { ManaCost = 1,} },
{"Kobold Stickyfinger", new CardData { ManaCost = 5, IsWeaponRemoval = true } },
{"Kronx Dragonhoof", new CardData { ManaCost = 6,  Attack = 6, Health = 6} },
{"Living Dragonbreath", new CardData { ManaCost = 3,} },
{"Parachute Brigand", new CardData { ManaCost = 2,} },
{"Platebreaker", new CardData { ManaCost = 5,} },
{"Sathrovarr", new CardData { ManaCost = 9,} },
{"Scalerider", new CardData { ManaCost = 3,} },
{"Shield of Galakrond", new CardData { ManaCost = 5,} },
{"Shu'ma", new CardData { ManaCost = 7,} },
{"Skyfin", new CardData { ManaCost = 5,} },
{"Tasty Flyfish", new CardData { ManaCost = 2,} },
{"Tentacled Menace", new CardData { ManaCost = 5,} },
{"Transmogrifier", new CardData { ManaCost = 2,} },
{"Troll Batrider", new CardData { ManaCost = 4,} },
{"Twin Tyrant", new CardData { ManaCost = 8,} },
{"Utharge Grapplesnipper", new CardData { ManaCost = 6,} },
{"Warrior Dragon", new CardData { ManaCost = 3,} },
{"Wing Commander", new CardData { ManaCost = 4,} },
{"Wyrmrest Purifier", new CardData { ManaCost = 2,} },
{"Zul'drak Ritualist", new CardData { ManaCost = 4,} },
{"Amber Watcher", new CardData { ManaCost = 5,} },
{"Bronze Explorer", new CardData { ManaCost = 3,} },
{"Dragonrider Tairitha", new CardData { ManaCost = 3,} },
{"Lightforged Crusader", new CardData { ManaCost = 7, Attack = 7, Health = 7} },
{"Lightforged Zealot", new CardData { ManaCost = 4, IsWeapon = true, Attack = 4, Health = 2} },
{"Self-Sharpening Sword", new CardData { ManaCost = 3, IsWeapon = true, Attack = 1, Health = 4, Spell="After ur hero attacks, gain+1 attack"} },
{"Nozdormu the Timeless", new CardData { ManaCost = 4,} },
{"Righteous Cause", new CardData { ManaCost = 1,} },
{"Sand Breath", new CardData { ManaCost = 1,} },
{"Sanctuary", new CardData { ManaCost = 2,} },
{"Sky Claw", new CardData { ManaCost = 3,} },
{"Breath of the Infinite", new CardData { ManaCost = 3,} },
{"Chronobreaker", new CardData { ManaCost = 5,} },
{"Disciple of Galakrond", new CardData { ManaCost = 1,  Attack = 1, Health = 2} },
{"Envoy of Lazul", new CardData { ManaCost = 2,} },
{"Fate Weaver", new CardData { ManaCost = 4,} },
{"Galacrond the Unspeakable", new CardData { ManaCost = 7,} },
{"Grave Rune", new CardData { ManaCost = 4,} },
{"Mindflayer Kaahrj", new CardData { ManaCost = 3, Attack = 3, Health = 3} },
{"Murozond the Infinite", new CardData { ManaCost = 8,} },
{"Time Rip", new CardData { ManaCost = 5, IsRemoval = true } },
{"Whispers of EVIL", new CardData { ManaCost = 0,} },
{"Bloodsail Flybooter", new CardData { ManaCost = 1,} },
{"Candle Breath", new CardData { ManaCost = 6,} },
{"Dragon's Hoard", new CardData { ManaCost = 1,} },
{"Pen Flinger", new CardData { ManaCost = 1, Attack = 1, Health = 1} },
{"Flik Skyshiv", new CardData { ManaCost = 6,} },
{"Galacrond the Nightmare", new CardData { ManaCost = 7,} },
{"Necrium Apothecary", new CardData { ManaCost = 4,} },
{"Praise Galakrond!", new CardData { ManaCost = 1,} },
{"Seal Fate", new CardData { ManaCost = 3,} },
{"Stowawy", new CardData { ManaCost = 5,} },
{"Umbral Skulker", new CardData { ManaCost = 4,} },
{"Waxadred", new CardData { ManaCost = 5,} },
{"Bandersmosh", new CardData { ManaCost = 5,} },
{"Corrupt Elementalist", new CardData { ManaCost = 5,} },
{"Cumulo-Maximus", new CardData { ManaCost = 5,} },
{"Dragon's Pack", new CardData { ManaCost = 1,} },
{"Galakrond the Tempest", new CardData { ManaCost = 7,} },
{"Invocation of Frost", new CardData { ManaCost = 1,} },
{"Lightning Breath", new CardData { ManaCost = 3,} },
{"Nithogg", new CardData { ManaCost = 6,} },
{"Squalhunter", new CardData { ManaCost = 4,} },
{"Storm's Wrath", new CardData { ManaCost = 1,} },
{"Surging Tempest", new CardData { ManaCost = 1,} },
{"Abyssal Summoner", new CardData { ManaCost = 6,} },
{"Crazed Netherwing", new CardData { ManaCost = 5, Aoe = true, Attack = 5, Health = 5} },
{"Dark Skies", new CardData { ManaCost = 3, Aoe = true} },
{"Dragonblight Cultist", new CardData { ManaCost = 3,} },
{"Fiendish Rites", new CardData { ManaCost = 3,} },
{"Galakrond the Wretched", new CardData { ManaCost = 7,} },
{"Nether Breath", new CardData { ManaCost = 2, IsBurn = true, Spell = "Lifesteal Damage 4" } },
{"Rain of Fire", new CardData { ManaCost = 1,} },
{"Void Drinker", new CardData { ManaCost = 5, IsTaunt = true, Spell = "Destroy Soul for +3/+3"} },
{"Valdris Felgorge", new CardData { ManaCost = 7,} },
{"Veiled Worshipper", new CardData { ManaCost = 4,} },
{"Zzeraku the Warped", new CardData { ManaCost = 8,} },
{"Ancharrr", new CardData { ManaCost = 3, IsWeapon = true,} },
{"Awaken", new CardData { ManaCost = 3,} },
{"Deathwing Mad Aspect", new CardData { ManaCost = 8, } },
{"EVIL Quartermaster", new CardData { ManaCost = 3,} },
{"Galakrond the Unbreakable", new CardData { ManaCost = 3,} },
{"Molten Breath", new CardData { ManaCost = 4,} },
{"Ramming Speed", new CardData { ManaCost = 3,} },
{"Ritual Chopper", new CardData { ManaCost = 2, IsWeapon = true,} },
{"Scion of Ruin", new CardData { ManaCost = 3, } },
{"Sky Raider", new CardData { ManaCost = 1,} },
{"Skybarge", new CardData { ManaCost = 3,} },
{"Garden Gnome", new CardData { ManaCost = 4 } },
{"Treenforcements", new CardData { ManaCost = 1 } },
{"Big Ol' Whelp", new CardData { ManaCost = 5 } },
{"Wisp", new CardData { ManaCost = 0 } },
{"Stampeding Roar", new CardData { ManaCost = 6 } },
{"Winged Guardian", new CardData { ManaCost = 7 } },
{"Rotnest Drake", new CardData { ManaCost = 5, IsRemoval = true } },
{"Frenzied Felwing", new CardData { ManaCost = 5 } },
 {"Animated Avalanche", new CardData { ManaCost = 7 } },
 {"Arcane Amplifier", new CardData { ManaCost = 3 } },
 {"Arcane Servant", new CardData { ManaCost = 2 } },
 {"Awaken!", new CardData { ManaCost = 3, Aoe = true} },
 {"Bestial Wrath", new CardData { ManaCost = 1 } },
 {"Bomb Wrangler", new CardData { ManaCost = 3 } },
 {"Bonfire Elemental", new CardData { ManaCost = 5 } },
 {"Boompistol Bully", new CardData { ManaCost = 5 } },
 {"Clockwork Automaton", new CardData { ManaCost = 5 } },
 {"Conjured Mirage", new CardData { ManaCost = 4 } },
 {"Embalming Ritual", new CardData { ManaCost = 1 } },
 {"Escaped Manasaber", new CardData { ManaCost = 4, Attack = 3, Health = 5, Spell = "Stealth add 1 mana on attack" } },
 {"Eye of the Storm", new CardData { ManaCost = 10 } },
 {"Fresh Scent", new CardData { ManaCost = 2 } },
 {"Galakrond the Nightmare", new CardData { ManaCost = 7 } },
 {"Galakrond the Unspeakable", new CardData { ManaCost = 7 } },
 {"Goblin Prank", new CardData { ManaCost = 2 } },
 {"Hailbringer", new CardData { ManaCost = 5 } },
 {"Hot Air Balloon", new CardData { ManaCost = 1 } },
 {"Hunting Mastiff", new CardData { ManaCost = 2 } },
 {"Licensed Adventurer", new CardData { ManaCost = 2 } },
 {"Omega Medic", new CardData { ManaCost = 3 } },
 {"Pharaoh's Blessing", new CardData { ManaCost = 6 } },
 {"Quicksand Elemental", new CardData { ManaCost = 2 } },
 {"Rising Winds", new CardData { ManaCost = 2 } },
 {"Risky Skipper", new CardData { ManaCost = 1 } },
 {"Scorch", new CardData { ManaCost = 4 } },
 {"Shadow Bolt", new CardData { ManaCost = 3 } },
 {"Shadowy Figure", new CardData { ManaCost = 2 } },
 {"Shotbot", new CardData { ManaCost = 2 } },
 {"Sky Gen'ral Kragg", new CardData { ManaCost = 4 } },
 {"Skyvateer", new CardData { ManaCost = 2 } },
 {"Stowaway", new CardData { ManaCost = 5 } },
 {"The Amazing Reno", new CardData { ManaCost = 10 } },
 {"The Beast Within", new CardData { ManaCost = 1 } },
 {"The Fist of Ra-den", new CardData { ManaCost = 4, IsWeapon = true } },
 {"War Master Voone", new CardData { ManaCost = 4 } },
 {"Water Elemental", new CardData { ManaCost = 4 } },
 {"Air Raid", new CardData { ManaCost = 1 } },
 {"Akama", new CardData { ManaCost = 3,  Attack = 3, Health = 4  } },
 {"Aldor Attendant", new CardData { ManaCost = 2, Attack = 1, Health = 3 } },
 {"Aldor Truthseeker", new CardData { ManaCost = 5, Attack = 4, Health = 6, IsTaunt = true } },
 {"Aldrachi Warblades", new CardData { ManaCost = 2, IsWeapon = true, Attack = 2, Health = 2 } },
 {"Altruis the Outcast", new CardData { ManaCost = 3, Attack = 4, Health = 2 } },
 {"Ashtongue Slayer", new CardData { ManaCost = 2,  Attack = 3, Health = 2, Spell = "Give a stealth minion +3 and imune"  } },
 {"Bane of Doom", new CardData { ManaCost = 0 } },
 {"Battlefiend", new CardData { ManaCost = 1,  Attack = 1, Health = 2 } },
 {"Blade Dance", new CardData { ManaCost = 2 } },
 {"Bloodboil Brute", new CardData { ManaCost = 7 } },
 {"Bogbeam", new CardData { ManaCost = 3 } },
 {"Boggspine Knuckles", new CardData { ManaCost = 5, IsWeapon = true } },
 {"Bonechewer Brawler", new CardData { ManaCost = 2,  Attack = 2, Health = 3 } },
 {"Burrowing Scorpid", new CardData { ManaCost = 4,  Attack = 5, Health = 2  } },
 {"Chaos Strike", new CardData { ManaCost = 2 } },
 {"Command the Illidari", new CardData { ManaCost = 5 } },
 {"Consume Magic", new CardData { ManaCost = 0 } },
 {"Coordinated Strike", new CardData { ManaCost = 3 } },
 {"Corsair Cache", new CardData { ManaCost = 2 } },
 {"Crimson Sigil Runner", new CardData { ManaCost = 1, Attack = 1, Health = 1 } },
 {"Exotic Mountseller", new CardData { ManaCost = 0 } },
 {"Eye Beam", new CardData { ManaCost = 1 } },
 {"Feast of Souls", new CardData { ManaCost = 0 } },
 {"Furious Felfin", new CardData { ManaCost = 2 } },
 {"Glaivebound Adept", new CardData { ManaCost = 5,  Attack = 6, Health = 4 } },
 {"Greyheart Sage", new CardData { ManaCost = 3,  Attack = 3, Health = 3  } },
 {"Guardian Augmerchant", new CardData { ManaCost = 1, Attack = 2, Health = 1 } },
 {"Hand of A'dal", new CardData { ManaCost = 2, Attack = 2, Health = 2 } },
 {"Hand of Gul'dan", new CardData { ManaCost = 6 } },
 {"Illidari Felblade", new CardData { ManaCost = 2, IsWeapon = true } },
 {"Immolation Aura", new CardData { ManaCost = 2 } },
 {"Imprisoned Antaen", new CardData { ManaCost = 6 } },
 {"Imprisoned Observer", new CardData { ManaCost = 3, Attack = 4, Health = 5, Aoe = true, Spell = "Dormant: on wake deal 2 damage" } },
 {"Warmaul Challenger", new CardData { ManaCost = 3 } },
 {"Soul Cleave", new CardData { ManaCost = 3 } },
 {"Magtheridon", new CardData { ManaCost = 4, Attack = 12, Health = 12, Aoe = true } },
 {"Inner Demon", new CardData { ManaCost = 0 } },
 {"Ironbark", new CardData { ManaCost = 2 } },
 {"Kael'thas Sunstrider", new CardData { ManaCost = 6 } },
 {"Kayn Sunfury", new CardData { ManaCost = 4,  Attack = 3, Health = 5 } },
 {"Lady Liadrin", new CardData { ManaCost = 7, Attack = 4, Health = 6} },
 {"Libram of Hope", new CardData { ManaCost = 9, Attack = 8, Health = 8, HasShield = true, IsTaunt = true, Heal = 8 } },
 {"Libram of Justice", new CardData { ManaCost = 6, IsWeapon = true, Attack = 1, Health = 4 } },
 {"Libram of Wisdom", new CardData { ManaCost = 2, Attack = 1, Health = 1 } },
 {"Maiev Shadowsong", new CardData { ManaCost = 4 } },
 {"Mana Burn", new CardData { ManaCost = 1 } },
 {"Marshspawn", new CardData { ManaCost = 3 } },
 {"Metamorphosis", new CardData { ManaCost = 5 } },
 {"Murgur Murgurgle", new CardData { ManaCost = 2, Attack = 2, Health = 1 } },
 {"Overconfident Orc", new CardData { ManaCost = 3 } },
 {"Overgrowth", new CardData { ManaCost = 4 } },
 {"Wrathspike Brute", new CardData { ManaCost = 5 } },
 {"Hulking Overfiend", new CardData { ManaCost = 8 } },
 {"Priestess of Fury", new CardData { ManaCost = 7 } },
 {"Satyr Overseer", new CardData { ManaCost = 3 } },
 {"Scrapyard Colossus", new CardData { ManaCost = 10 } },
 {"Serpentshrine Portal", new CardData { ManaCost = 3 } },
 {"Shadow Council", new CardData { ManaCost = 1 } },
 {"Shadowhoof Slayer", new CardData { ManaCost = 1 } },
  {"Ur'zul Horror", new CardData { ManaCost = 1 } },
 {"Skull of Gul'dan", new CardData { ManaCost = 6, Spell = "Draw 3, outcast reduce the cost by 3" } },
 {"Spectral Sight", new CardData { ManaCost = 2 } },
 {"Spymistress", new CardData { ManaCost = 1,  Attack = 3, Health = 1  } },
 {"The Dark Portal", new CardData { ManaCost = 4 } },
  {"Raging Felscreamer", new CardData { ManaCost = 4 } },
   {"Chaos Nova", new CardData { ManaCost = 5, Aoe = true } },
 {"Twin Slice", new CardData { ManaCost = 1 } },
 {"Twisted Knowledge", new CardData { ManaCost = 0 } },
 {"Umberwing", new CardData { ManaCost = 2, IsWeapon = true,  Attack = 1, Health = 2 } },
 {"Unstable Felbolt", new CardData { ManaCost = 1 } },
 {"Wrathscale Naga", new CardData { ManaCost = 3 } },
 {"Sethekk Veiweaver", new CardData { ManaCost = 3 } },

  {"Aeon Reaver", new CardData { ManaCost = 5 } },
 {"Ambush", new CardData { ManaCost = 2, IsSecret = true } },
 {"Apotheosis", new CardData { ManaCost = 3,  Attack = 2, Health = 3, Spell = "buff and grant life-steal" } },
 {"Ashtongue Battlelord", new CardData { ManaCost = 4 } },
 {"Bamboozle", new CardData { ManaCost = 2, IsSecret = true } },
 {"Blackjack Stunner", new CardData { ManaCost = 1, Attack = 1, Health = 2 } },
 {"Bogstrok Clacker", new CardData { ManaCost = 3 } },
 {"Coilfang Warlord", new CardData { ManaCost = 8 } },
 {"Dirty Tricks", new CardData { ManaCost = 2, IsSecret = true } },
 {"Fel Summoner", new CardData { ManaCost = 6 } },
 {"Frozen Shadoweaver", new CardData { ManaCost = 3 } },
 {"Fungal Fortunes", new CardData { ManaCost = 2 } },
 {"Glowfly Swarm", new CardData { ManaCost = 5 } },
 {"Hench-Clan Sneak", new CardData { ManaCost = 2 } },
 {"Kul Tiran Chaplain", new CardData { ManaCost = 3 } },
 {"Lady Vashj", new CardData { ManaCost = 3 } },
 {"Nagrand Slam", new CardData { ManaCost = 10 } },
 {"Overflow", new CardData { ManaCost = 4 } },
 {"Pit Commander", new CardData { ManaCost = 9 } },
 {"Power Infusion", new CardData { ManaCost = 0 } },
 {"Psyche Split", new CardData { ManaCost = 5 } },
 {"Reliquary of Souls", new CardData { ManaCost = 1 } },
 {"Renew", new CardData { ManaCost = 1 } },
 {"Scavenger's Ingenuity", new CardData { ManaCost = 2 } },
 {"Shadowjeweler Hanar", new CardData { ManaCost = 2, Attack = 1, Health = 4 } },
 {"Shattered Rumbler", new CardData { ManaCost = 5 } },
 {"Skeletal Dragon", new CardData { ManaCost = 7 } },
 {"Soul Mirror", new CardData { ManaCost = 7 } },
 {"Splitting Axe", new CardData { ManaCost = 4 } },
 {"Torrent", new CardData { ManaCost = 5 } },
 {"Totemic Might", new CardData { ManaCost = 0 } },
 {"Totemic Reflection", new CardData { ManaCost = 3 } },
 {"Totemic Surge", new CardData { ManaCost = 0 } },
 {"Worgen Infiltrator", new CardData { ManaCost = 2,  Attack = 2, Health = 1  } },
 {"Zixor, Apex Predator", new CardData { ManaCost = 3 } },
  {"Apexis Blast", new CardData { ManaCost = 5 } },
 {"Deep Freeze", new CardData { ManaCost = 8 } },
 {"Evocation", new CardData { ManaCost = 1 } },
 {"Font of Power", new CardData { ManaCost = 2 } },
 {"Incanter's Flow", new CardData { ManaCost = 2 } },
 {"Netherwind Portal", new CardData { ManaCost = 3, IsSecret = true } },
 {"Shadow Word: Ruin", new CardData { ManaCost = 4, Aoe = true, Spell = "Destroy minions with 5 or more attack" } },
{ "Kobold Sandtrooper", new CardData{ManaCost = 2} },
{ "Leper Gnome", new CardData{ManaCost = 1}},
 {"Al'ar", new CardData { ManaCost = 5 } },
 {"Bladestorm", new CardData { ManaCost = 3, Aoe = true } },
 {"Enhanced Dreadlord", new CardData { ManaCost = 8 } },
 {"Felfin Navigator", new CardData { ManaCost = 0 } },
 {"Gift of the Wild", new CardData { ManaCost = 8 } },
 {"Imprisoned Gan'arg", new CardData { ManaCost = 2 } },
 {"Kanrethad Ebonlocke", new CardData { ManaCost = 2 } },
 {"Keli'dan the Breaker", new CardData { ManaCost = 6 } },
 {"Ruststeed Raider", new CardData { ManaCost = 5 } },
 {"Scrap Golem", new CardData { ManaCost = 5 } },
 {"Sightless Watcher", new CardData { ManaCost = 2 } },
 {"Teron Gorefiend", new CardData { ManaCost = 3 } },
 {"Underlight Angling Rod", new CardData { ManaCost = 3, IsWeapon = true } },
 {"Warglaives of Azzinoth", new CardData { ManaCost = 5, IsWeapon = true  } },
 {"Adorable Infestation", new CardData { ManaCost = 1, Attack = 1, Health = 1, Spell = "summon a 1/1"  } },
 {"Animated Broomstick", new CardData { ManaCost = 1 } },
 {"Argent Braggart", new CardData { ManaCost = 2, Attack = 9, Health = 9 } },
 {"Athletic Studies", new CardData { ManaCost = 1 } },
 {"Blessing of Authority", new CardData { ManaCost = 5, Attack = 8, Health = 8 } },
 {"Brain Freeze", new CardData { ManaCost = 3 } },
 {"Brittlebone Destroyer", new CardData { ManaCost = 4 } },
 {"Bulwark of Azzinoth", new CardData { ManaCost = 1, IsWeapon = true  } },
 {"Cabal Acolyte", new CardData { ManaCost = 4, Attack = 2, Health = 6, Spell = "SB: steal minion with 2 or less attack"  } },
 {"Cleric of Scales", new CardData { ManaCost = 1 } },
 {"Coerce", new CardData { ManaCost = 3, IsRemoval = true } },
 {"Combustion", new CardData { ManaCost = 0 } },
 {"Commencement", new CardData { ManaCost = 7, Spell = "Summon a minnion from deck give it Taunt and DS" } },
 {"Cram Session", new CardData { ManaCost = 2 } },
 {"Cult Neophyte", new CardData { ManaCost = 3, Attack = 3, Health = 2 } },
 {"Cutting Class", new CardData { ManaCost = 5 } },
 {"Darkglare", new CardData { ManaCost = 3 } },
 {"Deathwing, Mad Aspect", new CardData { ManaCost = 8,  Attack = 12, Health = 12  } },
 {"Demon Companion", new CardData { ManaCost = 2, Spell ="Summon a random Demon companion" } },
 {"Devolving Missiles", new CardData { ManaCost = 1 } },
 {"Devout Pupil", new CardData { ManaCost = 6, Attack = 4, Health = 5, IsTaunt = true, HasShield = true } },
 {"Dimensional Ripper", new CardData { ManaCost = 10 } },
 {"Doctor Krastinov", new CardData { ManaCost = 5 } },
 {"Double Jump", new CardData { ManaCost = 1 } },
 {"Draconic Studies", new CardData { ManaCost = 1 } },
 {"Firebrand", new CardData { ManaCost = 3, Attack = 3, Health = 4, Spell = "SB: deal 4 damage randomly to enemy mins" } },
 {"First Day of School", new CardData { ManaCost = 0, Spell = "Add 2 1-cost minions to hand" } },
 {"Flesh Giant", new CardData { ManaCost = 8 } },
 {"Forest Warden Omu", new CardData { ManaCost = 6 } },
 {"Galakrond, the Nightmare", new CardData { ManaCost = 7 } },
 {"Galakrond, the Unbreakable", new CardData { ManaCost = 7 } },
 {"Galakrond, the Unspeakable", new CardData { ManaCost = 7 } },
 {"Galakrond, the Wretched", new CardData { ManaCost = 7 } },
 {"Germination", new CardData { ManaCost = 4 } },
 {"Gibberling", new CardData { ManaCost = 1 } },
 {"Gift of Luminance", new CardData { ManaCost = 3, Spell = "Summon 1/1 copy, give it Shield" } },
 {"Goody Two-Shields", new CardData { ManaCost = 3, Attack = 4, Health = 2 } },
 {"Guardian Animals", new CardData { ManaCost = 7 } },
 {"Headmaster Kel'Thuzad", new CardData { ManaCost = 5 } },
 {"High Abbess Alura", new CardData { ManaCost = 4, Attack = 3, Health = 6 } },
 {"Icicle", new CardData { ManaCost = 3 } },
 {"Imprisoned Vilefiend", new CardData { ManaCost = 2,  Attack = 3, Health = 5 } },
 {"Intrepid Initiate", new CardData { ManaCost = 1, Attack = 3, Health = 2  } },
 {"Jandice Barov", new CardData { ManaCost = 4 } },
 {"Kargath Bladefist", new CardData { ManaCost = 4,  Attack = 4, Health = 4  } },
 {"Lab Partner", new CardData { ManaCost = 1, Attack = 1, Health = 3 } },
 {"Lake Thresher", new CardData { ManaCost = 5 } },
 {"Lightning Bloom", new CardData { ManaCost = 0 } },
 {"Lord Barov", new CardData { ManaCost = 3 } },
 {"Lorekeeper Polkelt", new CardData { ManaCost = 4 } },
 {"Magehunter", new CardData { ManaCost = 0 } },
 {"Malygos, Aspect of Magic", new CardData { ManaCost = 5, Attack = 2, Health = 8 } },
 {"Manafeeder Panthara", new CardData { ManaCost = 2, Attack = 2, Health = 3 } },
 {"Marrowslicer", new CardData { ManaCost = 4, IsWeapon = true,  Attack = 4, Health = 2 } },
 {"Mindrender Illucia", new CardData { ManaCost = 3 } },
 {"Mozaki, Master Duelist", new CardData { ManaCost = 5,  Attack = 3, Health = 8 } },
 {"Nature Studies", new CardData { ManaCost = 1 } },
 {"Nethrandamus", new CardData { ManaCost = 0 } },
 {"Nightblade", new CardData { ManaCost = 5 } },
 {"Nightshade Matron", new CardData { ManaCost = 4,  Attack = 5, Health = 5 } },
 {"Onyx Magescribe", new CardData { ManaCost = 6,  Attack = 4, Health = 9, Spell = "Add 2 spells to hand" } },
 {"Plagiarize", new CardData { ManaCost = 2, IsSecret = true } },
 {"Pack Tactics", new CardData { ManaCost = 2, IsSecret = true } },
 {"Plague of Madness", new CardData { ManaCost = 1, IsWeapon = true, Spell = "Each plyr equips 2/2 poinson knife" } },
 {"Potion of Illusion", new CardData { ManaCost = 4 } },
 {"Primordial Studies", new CardData { ManaCost = 1 } },
 {"Raise Dead", new CardData { ManaCost = 0, Spell = "Damage self by 3, add 2 minions that have died to ur hand" } },
 {"Rattlegore", new CardData { ManaCost = 9, Attack = 9, Health = 9 } },
 {"Reaper's Scythe", new CardData { ManaCost = 4, IsWeapon = true,  Attack = 4, Health = 2  } },
 {"Runic Carvings", new CardData { ManaCost = 0 } },
 {"School Spirits", new CardData { ManaCost = 0 } },
 {"Secret Passage", new CardData { ManaCost = 1 } },
 {"Sethekk Veilweaver", new CardData { ManaCost = 2,  Attack = 2, Health = 3 } },
 {"Shadowlight Scholar", new CardData { ManaCost = 3,  Attack = 3, Health = 4 } },
 {"Shardshatter Mystic", new CardData { ManaCost = 3, Attack = 3, Health = 2, Aoe = true } },
 {"Shield of Honor", new CardData { ManaCost = 0 } },
 {"Shieldbearer", new CardData { ManaCost = 0 } },
 {"Sneaky Delinquent", new CardData { ManaCost = 2,  Attack = 3, Health = 1  } },
 {"Soul Shear", new CardData { ManaCost = 2 } },
 {"Soulciologist Malicia", new CardData { ManaCost = 7, Attack = 5, Health = 5, Spell = "BC: summon a 3/3 rush foreach fragment" } },
 {"Soulshard Lapidary", new CardData { ManaCost = 5, Attack = 5, Health = 5 } },
 {"Speaker Gidra", new CardData { ManaCost = 3 } },
 {"Sphere of Sapience", new CardData { ManaCost = 1, IsWeapon = true  } },
 {"Spirit Jailer", new CardData { ManaCost = 1, Attack = 1, Health = 3 } },
 {"Survival of the Fittest", new CardData { ManaCost = 10 } },
 {"Sword and Board", new CardData { ManaCost = 2 } },
 {"Teacher's Pet", new CardData { ManaCost = 5, Attack = 4, Health = 5, Spell = "Taunt and Deathrattle" } },
 {"Totem Goliath", new CardData { ManaCost = 5 } },
 {"Tour Guide", new CardData { ManaCost = 1, Attack = 1, Health = 1  } },
 {"Transfer Student", new CardData { ManaCost = 4 } },
 {"Trick Totem", new CardData { ManaCost = 2, Attack = 0, Health = 3 } },
 {"Troublemaker", new CardData { ManaCost = 8 } },
 {"Twilight Runner", new CardData { ManaCost = 5 } },
 {"Voracious Reader", new CardData { ManaCost = 2,  Attack = 1, Health = 3, Spell = "eot:draw til ur hand has 3" } },
 {"Vulpera Toxinblade", new CardData { ManaCost = 0 } },
 {"Wand Thief", new CardData { ManaCost = 1, Attack = 1, Health = 2 } },
 {"Wave of Apathy", new CardData { ManaCost = 1 } },
 {"Wolpertinger", new CardData { ManaCost = 1, Attack = 1, Health = 1, Spell = "summons a copy"  } },
 {"Wretched Tutor", new CardData { ManaCost = 4, Aoe = true,  Attack = 2, Health = 5 } },
 {"Ysera, Unleashed", new CardData { ManaCost = 9, Attack = 4, Health = 12 } },
			};
        }

    }

    public class CardData
    {
        public int ManaCost { get; set; }
        public bool Aoe { get; set; }
		public bool IsSecret { get; set; }
		public bool IsWeapon { get; set; }
		public bool IsWeaponRemoval { get; set; }
		public bool IsRemoval { get; set; }
		public bool IsBurn { get; set; }
		public bool IsTaunt { get; set; }
		public bool HasShield { get; set; }
		public int? Heal { get; set; }
		public string Spell { get; set; }

		public int? Attack { get; set; }
		public int? Health { get; set; }
	}
}